load ../systems/ibos-preds.maude
load ../../rltool-lib.maude

mod IMPORTS is
  pr CONFLUENCE-TOOLS .
  pr SIMPLE-CRITPAIR .
endm

mod TEST is
  pr IMPORTS *
    (op __ : EquationSet EquationSet -> EquationSet to _eq_,
     op __ : SubsortDeclSet SubsortDeclSet -> SubsortDeclSet to _sbs_
    ) .

  op pid : -> Module .
  eq pid = upModule('PROC-ID,true) .

  op mfe : -> Module .
  eq mfe = upModule('MSG-FVP-EXT,true) .

  op afe : -> Module .
  eq afe = upModule('ATTRIBUTE-FVP-EXT,true) .

  op ibos : -> Module .
  eq ibos = upModule('IBOS-PREDS,true) .
endm

--- set print conceal on .
--- print conceal _eq_ _sbs_ .
--- NOTE: based on source code check and reading CRC paper,
---       all context-joinability/unfeasibility checks only use search
---       so they can occur in the original module in this case
red crcContextJoinableAndUnfeasibleCPs(ibos,toStdCritPairs(subsume(ibos,simplify(ibos,getSimpleCritPairs(deleteIdEqs(removeIds(ibos,non-handled))))))) .
quit
