load ../systems/ibos-preds.maude
load ~/work/mta/mta.maude
(check-AvCrpo IBOS-PREDS assuming
    ('NA:NeAttributeSet : 'none.AttributeSet)
  | ('L:Label           : 'nolabel.MaybeLabel)
  | ('Z:NzNat           : '0.Nat)
  | ('NM:NeMessageList  : 'mt.MessageList)
  | ('NM:NeMessageList  : 'nolist.MaybeMessageList)
  | ('L:Label           : 'mtLL.LabelList)
  | ('L:Label           : 'mtLS.LabelSet)
  | ('P:ProcessId       : 'none.NullProcId)
.)
quit
