load ../systems/ibos-preds.maude
load ../../rltool-lib.maude

fmod TEST is
  pr UNIFIERS .                  --- metaMatch/safeMatch variants
  pr CONSTRAINED-TERMSET-MATCH . --- #match
  pr REACH-PROOF-GOALSET .       --- goalsByMatch, !goalsByMatch, #goalsByMatch
  pr META-PARSE .                --- stringToTerm (easier testing)

  op ibos : -> Module [ctor] .
  eq ibos = upModule('IBOS-PREDS,true) .

  op ibos_ : String -> Term .
  eq ibos S:String = stringToTerm(ibos,S:String) .

  ops t1 t1' t2 : -> Term [memo] .
  eq t1  = ibos "< W:ConcWebProcId | A:AttributeSet  > \
                 C:Configuration" .

  eq t1' = ibos "< W:ConcWebProcId | A:AttributeSet  > \
                 C':Configuration" .

  eq t2  = ibos "< W:ConcWebProcId | A:AttributeSet  > \
                 < N:ConcNetProcId | A':AttributeSet > \
                 C:Configuration" .

  ops ct0 ct1 ct1' ct2 : -> QFCTerm [memo] .
  eq ct0  = ('0.Nat | tt) .
  eq ct1  = (t1 | 'conf-dupl?[t1 ] ?= 'true.Bool) .
  eq ct1' = (t1 | 'conf-dupl?[t1'] ?= 'true.Bool) .
  eq ct2  = (t2 | 'conf-dupl?[t1 ] ?= 'true.Bool) .

  ops g1 g1' g2 : -> ProofGoal .
  eq g1  = [none,0,pause,active,none,ct1  => ct0] .
  eq g1' = [none,0,pause,active,none,ct1' => ct0] .
  eq g2  = [none,0,pause,active,none,ct2  => ct0] .
endfm

red wellFormed(ibos,t1)  .
red wellFormed(ibos,t2)  .
red wellFormed(ibos,ct1) .
red wellFormed(ibos,ct2) .
red wellFormed(ibos,getbody(g1)) .

--- t1 matches g1 and g2
red goalsByMatch(ibos,t1,g1 && g2) == g1 && g2 .
--- t2 only matches g2
red goalsByMatch(ibos,t2,g1 && g2) == g2 .
--- ct1 only matches g1 because of shared variable C in term and condition
red goalsByMatch(ibos,ct1 , g1 && g2) == g1 .
--- ct1' matches g1 and g2 because C variable is not shared between term and condition
red goalsByMatch(ibos,ct1', g1 && g2) == g1 && g2 .

--- Same tests with # version

--- t1 matches g1 and g2
red toGoalSet(#goalsByMatch(ibos,t1,g1 && g2)) == g1 && g2 .
--- t2 only matches g2
red toGoalSet(#goalsByMatch(ibos,t2,g1 && g2)) == g2 .
--- ct1 only matches g1 because of shared variable C in term and condition
red toGoalSet(#goalsByMatch(ibos,ct1 , g1 && g2)) == g1 .
--- ct1' matches g1 and g2 because C variable is not shared between term and condition
red toGoalSet(#goalsByMatch(ibos,ct1', g1 && g2)) == g1 && g2 .

quit
