set include BOOL off .

fmod IBOS-SOP-FVP-NOID is
  sorts AbsNetProcId AbsPipeId AbsProcessId AbsWebProcId Attribute AttributeSet Bool Bool? Configuration DisplayId EmptyAttributeSet EmptyConfiguration EmptyMessageList FetchMsg FetchMsgType HasFetchMsgList KernelId Label LabelList LabelSet MaybeLabel Message Message? MessageList MsgType NICId Nat NeAttributeSet NeConfiguration NeNetProcInfoSet NeWebProcInfoSet NetProcId NetProcInfo NetProcInfoSet NetWebProcConfig NetWebProcId NetWebProcNeConfig NetWebProcObject NonFetchMsg NonFetchMsgList NonFetchMsgType NonNetPipeId NonNetProcId NonPipeId NonRetFetchMsg NonRetFetchMsgType NonRetMsg NonRetMsgType NonWebPipeId NonWebProcId NzNat Object PipeId Policy PolicySet Pred ProcessId RetMsg RetMsgType State UIId WebProcId WebProcInfo WebProcInfoSet WebProcMgrId .
  subsort AbsNetProcId < AbsPipeId .
  subsort AbsWebProcId < AbsPipeId .
  subsort Attribute < NeAttributeSet .
  subsort Bool < Bool? .
  subsort DisplayId < NonPipeId .
  subsort EmptyAttributeSet < AttributeSet .
  subsort EmptyConfiguration < Configuration .
  subsort EmptyConfiguration < NetWebProcConfig .
  subsort EmptyMessageList < MessageList .
  subsort EmptyMessageList < NonFetchMsgList .
  subsort FetchMsg < HasFetchMsgList .
  subsort FetchMsg < NonRetMsg .
  subsort FetchMsgType < NonRetMsgType .
  subsort HasFetchMsgList < MessageList .
  subsort KernelId < NonPipeId .
  subsort Label < LabelList .
  subsort Label < LabelSet .
  subsort Label < MaybeLabel .
  subsort Message < Message? .
  subsort Message < MessageList .
  subsort NICId < NonPipeId .
  subsort NeAttributeSet < AttributeSet .
  subsort NeConfiguration < Configuration .
  subsort NeNetProcInfoSet < NetProcInfoSet .
  subsort NeWebProcInfoSet < WebProcInfoSet .
  subsort NetProcId < AbsNetProcId .
  subsort NetProcId < NetWebProcId .
  subsort NetProcId < NonWebPipeId .
  subsort NetProcId < PipeId .
  subsort NetProcInfo < NeNetProcInfoSet .
  subsort NetProcInfo < NetProcInfoSet .
  subsort NetWebProcConfig < Configuration .
  subsort NetWebProcId < PipeId .
  subsort NetWebProcNeConfig < NeConfiguration .
  subsort NetWebProcNeConfig < NetWebProcConfig .
  subsort NetWebProcObject < NetWebProcNeConfig .
  subsort NetWebProcObject < Object .
  subsort NonFetchMsg < Message .
  subsort NonFetchMsg < NonFetchMsgList .
  subsort NonFetchMsgList < MessageList .
  subsort NonFetchMsgType < MsgType .
  subsort NonNetPipeId < NonNetProcId .
  subsort NonNetPipeId < PipeId .
  subsort NonNetProcId < ProcessId .
  subsort NonPipeId < NonNetProcId .
  subsort NonPipeId < NonWebProcId .
  subsort NonPipeId < ProcessId .
  subsort NonRetFetchMsg < NonFetchMsg .
  subsort NonRetFetchMsg < NonRetMsg .
  subsort NonRetFetchMsgType < NonFetchMsgType .
  subsort NonRetFetchMsgType < NonRetMsgType .
  subsort NonRetMsg < Message .
  subsort NonRetMsgType < MsgType .
  subsort NonWebPipeId < NonWebProcId .
  subsort NonWebPipeId < PipeId .
  subsort NonWebProcId < ProcessId .
  subsort NzNat < Nat .
  subsort Object < NeConfiguration .
  subsort PipeId < AbsPipeId .
  subsort PipeId < ProcessId .
  subsort Policy < PolicySet .
  subsort ProcessId < AbsProcessId .
  subsort RetMsg < NonFetchMsg .
  subsort RetMsgType < NonFetchMsgType .
  subsort UIId < NonNetPipeId .
  subsort UIId < NonWebPipeId .
  subsort UIId < PipeId .
  subsort WebProcId < AbsWebProcId .
  subsort WebProcId < NetWebProcId .
  subsort WebProcId < NonNetPipeId .
  subsort WebProcId < PipeId .
  subsort WebProcInfo < NeWebProcInfoSet .
  subsort WebProcInfo < WebProcInfoSet .
  subsort WebProcMgrId < NonPipeId .
  op 0 : -> Nat
    [ctor metadata "0"] .
  op 1 : -> NzNat
    [ctor metadata "15"] .
  op <_|_> : NetWebProcId AttributeSet -> NetWebProcObject
    [ctor metadata "33"] .
  op <_|_> : ProcessId AttributeSet -> Object
    [ctor metadata "33"] .
  op MSG-FETCH-URL : -> FetchMsgType
    [ctor metadata "46"] .
  op MSG-FETCH-URL : -> MsgType
    [ctor metadata "46"] .
  op MSG-NEW-URL : -> MsgType
    [ctor metadata "45"] .
  op MSG-NEW-URL : -> NonRetFetchMsgType
    [ctor metadata "45"] .
  op MSG-RETURN-URL : -> MsgType
    [ctor metadata "47"] .
  op MSG-RETURN-URL : -> RetMsgType
    [ctor metadata "47"] .
  op MSG-SWITCH-TAB : -> MsgType
    [ctor metadata "48"] .
  op MSG-SWITCH-TAB : -> NonRetFetchMsgType
    [ctor metadata "48"] .
  op URL : Label -> Attribute
    [ctor metadata "57"] .
  op _&_ : LabelSet LabelSet -> LabelSet
    [assoc comm id: mtLS ctor metadata "44"] .
  op _+_ : Nat Nat -> Nat
    [assoc comm id: 0 ctor metadata "16"] .
  op _+_ : NzNat Nat -> NzNat
    [assoc comm id: 0 ctor metadata "16"] .
  op _;_ : LabelList LabelList -> LabelList
    [assoc ctor metadata "43 mtLL.LabelList"] .
  op _<=_ : Nat Nat -> Bool
    [metadata "19"] .
  op _<_ : Nat Nat -> Bool
    [metadata "18"] .
  op _@_ : EmptyMessageList EmptyMessageList -> EmptyMessageList
    [assoc ctor metadata "52 mt.EmptyMessageList"] .
  op _@_ : HasFetchMsgList HasFetchMsgList -> HasFetchMsgList
    [assoc ctor metadata "52 mt.EmptyMessageList"] .
  op _@_ : HasFetchMsgList NonFetchMsgList -> HasFetchMsgList
    [assoc ctor metadata "52 mt.EmptyMessageList"] .
  op _@_ : MessageList MessageList -> MessageList
    [assoc ctor metadata "52 mt.EmptyMessageList"] .
  op _@_ : NonFetchMsgList HasFetchMsgList -> HasFetchMsgList
    [assoc ctor metadata "52 mt.EmptyMessageList"] .
  op _@_ : NonFetchMsgList NonFetchMsgList -> NonFetchMsgList
    [assoc ctor metadata "52 mt.EmptyMessageList"] .
  op __ : Configuration Configuration -> Configuration
    [assoc comm id:(none).EmptyConfiguration ctor metadata "35"] .
  op __ : EmptyConfiguration EmptyConfiguration -> EmptyConfiguration
    [assoc comm id:(none).EmptyConfiguration ctor metadata "35"] .
  op __ : NeConfiguration Configuration -> NeConfiguration
    [assoc comm id:(none).EmptyConfiguration ctor metadata "35"] .
  op __ : NetWebProcConfig NetWebProcConfig -> NetWebProcConfig
    [assoc comm id:(none).EmptyConfiguration ctor metadata "35"] .
  op __ : NetWebProcNeConfig NetWebProcConfig -> NetWebProcNeConfig
    [assoc comm id:(none).EmptyConfiguration ctor metadata "35"] .
  op _`,_ : AttributeSet AttributeSet -> AttributeSet
    [assoc comm id:(none).EmptyAttributeSet ctor metadata "34"] .
  op _`,_ : AttributeSet NeAttributeSet -> NeAttributeSet
    [assoc comm id:(none).EmptyAttributeSet ctor metadata "34"] .
  op _`,_ : EmptyAttributeSet EmptyAttributeSet -> EmptyAttributeSet
    [assoc comm id:(none).EmptyAttributeSet ctor metadata "34"] .
  op _`,np_ : NeNetProcInfoSet NetProcInfoSet -> NeNetProcInfoSet
    [assoc comm id: mtNPIS ctor metadata "75"] .
  op _`,np_ : NetProcInfoSet NetProcInfoSet -> NetProcInfoSet
    [assoc comm id: mtNPIS ctor metadata "75"] .
  op _`,ps_ : PolicySet PolicySet -> PolicySet
    [assoc comm id: mtPS ctor metadata "66"] .
  op _`,wp_ : NeWebProcInfoSet WebProcInfoSet -> NeWebProcInfoSet
    [assoc comm id: mtWPIS ctor metadata "72"] .
  op _`,wp_ : WebProcInfoSet WebProcInfoSet -> WebProcInfoSet
    [assoc comm id: mtWPIS ctor metadata "72"] .
  op _and_ : Bool Bool -> Bool
    [assoc comm prec 50 metadata "12"] .
  op _or_ : Bool Bool -> Bool
    [assoc comm metadata "13"] .
  op _~l_ : Label Label -> Bool
    [comm metadata "42"] .
  op _~m_ : MsgType MsgType -> Bool
    [comm metadata "51"] .
  op _~n_ : Nat Nat -> Bool
    [comm metadata "22"] .
  op _~p_ : AbsProcessId AbsProcessId -> Bool
    [comm metadata "32"] .
  op `{_`} : Configuration -> State
    [ctor metadata "36"] .
  op about-blank : -> Label
    [ctor metadata "37"] .
  op activeWebapp : WebProcId -> Attribute
    [ctor metadata "78"] .
  op display : -> DisplayId
    [ctor metadata "29"] .
  op displayedContent : Label -> Attribute
    [ctor metadata "79"] .
  op displayedTopBar : Label -> Attribute
    [ctor metadata "77"] .
  op false : -> Bool
    [ctor special(id-hook SystemFalse)metadata "11"] .
  op fromKernel : MessageList -> Attribute
    [ctor metadata "53"] .
  op handledCurrently : Message? -> Attribute
    [ctor metadata "70"] .
  op in : LabelList -> Attribute
    [ctor metadata "60"] .
  op kernel : -> KernelId
    [ctor metadata "23"] .
  op loading : Bool -> Attribute
    [ctor metadata "58"] .
  op mem-in : MaybeLabel -> Attribute
    [ctor metadata "63"] .
  op mem-out : MaybeLabel -> Attribute
    [ctor metadata "62"] .
  op msg : AbsPipeId AbsPipeId FetchMsgType Label -> FetchMsg
    [ctor metadata "49"] .
  op msg : AbsPipeId AbsPipeId MsgType Label -> Message
    [ctor metadata "49"] .
  op msg : AbsPipeId AbsPipeId NonFetchMsgType Label -> NonFetchMsg
    [ctor metadata "49"] .
  op msg : AbsPipeId AbsPipeId NonRetFetchMsgType Label -> NonRetFetchMsg
    [ctor metadata "49"] .
  op msg : AbsPipeId AbsPipeId NonRetMsgType Label -> NonRetMsg
    [ctor metadata "49"] .
  op msg : AbsPipeId AbsPipeId RetMsgType Label -> RetMsg
    [ctor metadata "49"] .
  op msgPolicy : PolicySet -> Attribute
    [ctor metadata "67"] .
  op mt : -> EmptyMessageList
    [ctor metadata "5"] .
  op mt : -> MessageList
    [ctor metadata "5"] .
  op mtLL : -> LabelList
    [ctor metadata "3"] .
  op mtLS : -> LabelSet
    [ctor metadata "4"] .
  op mtNPIS : -> NetProcInfoSet
    [ctor metadata "8"] .
  op mtPS : -> PolicySet
    [ctor metadata "6"] .
  op mtWPIS : -> WebProcInfoSet
    [ctor metadata "7"] .
  op netlabels : NetProcInfoSet -> Attribute
    [ctor metadata "76"] .
  op network : Nat -> NetProcId
    [ctor metadata "27"] .
  op network : -> AbsNetProcId
    [ctor metadata "26"] .
  op nextNPN : Nat -> Attribute
    [ctor metadata "69"] .
  op nextWPN : Nat -> Attribute
    [ctor metadata "55"] .
  op nic : -> NICId
    [ctor metadata "30"] .
  op nic-in : LabelList -> Attribute
    [ctor metadata "65"] .
  op nic-out : LabelSet -> Attribute
    [ctor metadata "64"] .
  op nolabel : -> MaybeLabel
    [ctor metadata "39"] .
  op none : -> EmptyAttributeSet
    [ctor metadata "1"] .
  op none : -> EmptyConfiguration
    [ctor metadata "2"] .
  op none : -> Message?
    [ctor metadata "50"] .
  op not_ : Bool -> Bool
    [metadata "14"] .
  op out : LabelList -> Attribute
    [ctor metadata "61"] .
  op pi : WebProcId Label -> WebProcInfo
    [ctor metadata "71"] .
  op pi : NetProcId Label Label -> NetProcInfo
    [ctor metadata "74"] .
  op policy : AbsPipeId AbsPipeId MsgType -> Policy
    [ctor metadata "68"] .
  op rendered : Label -> Attribute
    [ctor metadata "56"] .
  op returnTo : PipeId -> Attribute
    [ctor metadata "59"] .
  op toKernel : MessageList -> Attribute
    [ctor metadata "54"] .
  op true : -> Bool
    [ctor special(id-hook SystemTrue)metadata "10"] .
  op tt : -> Pred
    [ctor metadata "9"] .
  op ui : -> UIId
    [ctor metadata "28"] .
  op url : Nat -> Label
    [ctor metadata "38"] .
  op webapp : Nat -> WebProcId
    [ctor metadata "25"] .
  op webapp : -> AbsWebProcId
    [ctor metadata "24"] .
  op webappmgr : -> WebProcMgrId
    [ctor metadata "31"] .
  op weblabels : WebProcInfoSet -> Attribute
    [ctor metadata "73"] .
  eq MSG-FETCH-URL ~m M:NonFetchMsgType
    = false .
  eq MSG-FETCH-URL ~m MSG-NEW-URL
    = false .
  eq MSG-FETCH-URL ~m MSG-SWITCH-TAB
    = false .
  eq MSG-NEW-URL ~m MSG-SWITCH-TAB
    = false .
  eq MSG-RETURN-URL ~m M:NonRetMsgType
    = false .
  eq MSG-RETURN-URL ~m MSG-SWITCH-TAB
    = false .
  eq X:MsgType ~m X:MsgType
    = true .
  eq X2:[LabelList,LabelSet,MaybeLabel]; mtLL
    = X2:[LabelList,LabelSet,MaybeLabel] [metadata "id" variant] .
  eq mtLL ; X2:[LabelList,LabelSet,MaybeLabel]
    = X2:[LabelList,LabelSet,MaybeLabel] [metadata "id" variant] .
  eq (X2:[LabelList,LabelSet,MaybeLabel]; mtLL); Y2:[LabelList,LabelSet,MaybeLabel]
    = X2:[LabelList,LabelSet,MaybeLabel]; Y2:[LabelList,LabelSet,MaybeLabel] [metadata "id" variant] .
  eq N:Nat <= N:Nat + M:Nat
    = true [variant] .
  eq (N:Nat + P:NzNat)<= N:Nat
    = false [variant] .
  eq N:Nat < N:Nat + P:NzNat
    = true [variant] .
  eq (N:Nat + M:Nat)< N:Nat
    = false [variant] .
  eq X3:[Message?,MessageList]@ mt
    = X3:[Message?,MessageList] [metadata "id" variant] .
  eq mt @ X3:[Message?,MessageList]
    = X3:[Message?,MessageList] [metadata "id" variant] .
  eq (X3:[Message?,MessageList]@ mt)@ Y3:[Message?,MessageList]
    = X3:[Message?,MessageList]@ Y3:[Message?,MessageList] [metadata "id" variant] .
  eq false and B:Bool
    = false [variant] .
  eq true and B:Bool
    = B:Bool [variant] .
  eq false or B:Bool
    = B:Bool [variant] .
  eq true or B:Bool
    = true [variant] .
  eq L:Label ~l L:Label
    = true [variant] .
  eq about-blank ~l url(N:Nat)
    = false [variant] .
  eq url(N:Nat)~l url(N':Nat)
    = N:Nat ~n N':Nat [variant] .
  eq N:Nat ~n N:Nat
    = true [variant] .
  eq N:Nat ~n N:Nat + P:NzNat
    = false [variant] .
  eq DiId:DisplayId ~p KeId:KernelId
    = false [variant] .
  eq DiId:DisplayId ~p NPId:NetProcId
    = false [variant] .
  eq DiId:DisplayId ~p UiId:UIId
    = false [variant] .
  eq DiId:DisplayId ~p WPId:WebProcId
    = false [variant] .
  eq DiId:DisplayId ~p WPMId:WebProcMgrId
    = false [variant] .
  eq KeId:KernelId ~p NPId:NetProcId
    = false [variant] .
  eq KeId:KernelId ~p UiId:UIId
    = false [variant] .
  eq KeId:KernelId ~p WPId:WebProcId
    = false [variant] .
  eq NPId:NetProcId ~p UiId:UIId
    = false [variant] .
  eq NPId:NetProcId ~p WPId:WebProcId
    = false [variant] .
  eq PId:ProcessId ~p PId:ProcessId
    = true [variant] .
  eq UiId:UIId ~p WPId:WebProcId
    = false [variant] .
  eq WPMId:WebProcMgrId ~p KeId:KernelId
    = false [variant] .
  eq WPMId:WebProcMgrId ~p NPId:NetProcId
    = false [variant] .
  eq WPMId:WebProcMgrId ~p UiId:UIId
    = false [variant] .
  eq WPMId:WebProcMgrId ~p WPId:WebProcId
    = false [variant] .
  eq network ~p network(N:Nat)
    = false [variant] .
  eq webapp ~p webapp(N:Nat)
    = false [variant] .
  eq network(N:Nat)~p network(N':Nat)
    = N:Nat ~n N':Nat [variant] .
  eq webapp(N:Nat)~p webapp(N':Nat)
    = N:Nat ~n N':Nat [variant] .
  eq not false
    = true [variant] .
  eq not true
    = false [variant] .
endfm
