set include BOOL off .

mod IBOS-SOP-NOID is
  sorts AbsNetProcId AbsPipeId AbsProcessId AbsWebProcId Attribute AttributeSet Bool Bool? Configuration DisplayId EmptyAttributeSet EmptyConfiguration EmptyMessageList FetchMsg FetchMsgType HasFetchMsgList KernelId Label LabelList LabelSet MaybeLabel Message Message? MessageList MsgType NICId Nat NeAttributeSet NeConfiguration NeNetProcInfoSet NeWebProcInfoSet NetProcId NetProcInfo NetProcInfoSet NetWebProcConfig NetWebProcId NetWebProcNeConfig NetWebProcObject NonFetchMsg NonFetchMsgList NonFetchMsgType NonNetPipeId NonNetProcId NonPipeId NonRetFetchMsg NonRetFetchMsgType NonRetMsg NonRetMsgType NonWebPipeId NonWebProcId NzNat Object PipeId Policy PolicySet Pred ProcessId RetMsg RetMsgType State UIId WebProcId WebProcInfo WebProcInfoSet WebProcMgrId .
  subsort AbsNetProcId < AbsPipeId .
  subsort AbsWebProcId < AbsPipeId .
  subsort Attribute < NeAttributeSet .
  subsort Bool < Bool? .
  subsort DisplayId < NonPipeId .
  subsort EmptyAttributeSet < AttributeSet .
  subsort EmptyConfiguration < Configuration .
  subsort EmptyConfiguration < NetWebProcConfig .
  subsort EmptyMessageList < MessageList .
  subsort EmptyMessageList < NonFetchMsgList .
  subsort FetchMsg < HasFetchMsgList .
  subsort FetchMsg < NonRetMsg .
  subsort FetchMsgType < NonRetMsgType .
  subsort HasFetchMsgList < MessageList .
  subsort KernelId < NonPipeId .
  subsort Label < LabelList .
  subsort Label < LabelSet .
  subsort Label < MaybeLabel .
  subsort Message < Message? .
  subsort Message < MessageList .
  subsort NICId < NonPipeId .
  subsort NeAttributeSet < AttributeSet .
  subsort NeConfiguration < Configuration .
  subsort NeNetProcInfoSet < NetProcInfoSet .
  subsort NeWebProcInfoSet < WebProcInfoSet .
  subsort NetProcId < AbsNetProcId .
  subsort NetProcId < NetWebProcId .
  subsort NetProcId < NonWebPipeId .
  subsort NetProcId < PipeId .
  subsort NetProcInfo < NeNetProcInfoSet .
  subsort NetProcInfo < NetProcInfoSet .
  subsort NetWebProcConfig < Configuration .
  subsort NetWebProcId < PipeId .
  subsort NetWebProcNeConfig < NeConfiguration .
  subsort NetWebProcNeConfig < NetWebProcConfig .
  subsort NetWebProcObject < NetWebProcNeConfig .
  subsort NetWebProcObject < Object .
  subsort NonFetchMsg < Message .
  subsort NonFetchMsg < NonFetchMsgList .
  subsort NonFetchMsgList < MessageList .
  subsort NonFetchMsgType < MsgType .
  subsort NonNetPipeId < NonNetProcId .
  subsort NonNetPipeId < PipeId .
  subsort NonNetProcId < ProcessId .
  subsort NonPipeId < NonNetProcId .
  subsort NonPipeId < NonWebProcId .
  subsort NonPipeId < ProcessId .
  subsort NonRetFetchMsg < NonFetchMsg .
  subsort NonRetFetchMsg < NonRetMsg .
  subsort NonRetFetchMsgType < NonFetchMsgType .
  subsort NonRetFetchMsgType < NonRetMsgType .
  subsort NonRetMsg < Message .
  subsort NonRetMsgType < MsgType .
  subsort NonWebPipeId < NonWebProcId .
  subsort NonWebPipeId < PipeId .
  subsort NonWebProcId < ProcessId .
  subsort NzNat < Nat .
  subsort Object < NeConfiguration .
  subsort PipeId < AbsPipeId .
  subsort PipeId < ProcessId .
  subsort Policy < PolicySet .
  subsort ProcessId < AbsProcessId .
  subsort RetMsg < NonFetchMsg .
  subsort RetMsgType < NonFetchMsgType .
  subsort UIId < NonNetPipeId .
  subsort UIId < NonWebPipeId .
  subsort UIId < PipeId .
  subsort WebProcId < AbsWebProcId .
  subsort WebProcId < NetWebProcId .
  subsort WebProcId < NonNetPipeId .
  subsort WebProcId < PipeId .
  subsort WebProcInfo < NeWebProcInfoSet .
  subsort WebProcInfo < WebProcInfoSet .
  subsort WebProcMgrId < NonPipeId .
  op 0 : -> Nat
    [ctor metadata "0"] .
  op 1 : -> NzNat
    [ctor metadata "15"] .
  op <_|_> : NetWebProcId AttributeSet -> NetWebProcObject
    [ctor metadata "33"] .
  op <_|_> : ProcessId AttributeSet -> Object
    [ctor metadata "33"] .
  op MSG-FETCH-URL : -> FetchMsgType
    [ctor metadata "46"] .
  op MSG-FETCH-URL : -> MsgType
    [ctor metadata "46"] .
  op MSG-NEW-URL : -> MsgType
    [ctor metadata "45"] .
  op MSG-NEW-URL : -> NonRetFetchMsgType
    [ctor metadata "45"] .
  op MSG-RETURN-URL : -> MsgType
    [ctor metadata "47"] .
  op MSG-RETURN-URL : -> RetMsgType
    [ctor metadata "47"] .
  op MSG-SWITCH-TAB : -> MsgType
    [ctor metadata "48"] .
  op MSG-SWITCH-TAB : -> NonRetFetchMsgType
    [ctor metadata "48"] .
  op URL : Label -> Attribute
    [ctor metadata "57"] .
  op _!a : AttributeSet -> AttributeSet
    [metadata "100"] .
  op _!c : Configuration -> Configuration
    [metadata "105"] .
  op _&_ : LabelSet LabelSet -> LabelSet
    [assoc comm id: mtLS ctor metadata "44"] .
  op _+_ : Nat Nat -> Nat
    [assoc comm id: 0 ctor metadata "16"] .
  op _+_ : NzNat Nat -> NzNat
    [assoc comm id: 0 ctor metadata "16"] .
  op _;_ : LabelList LabelList -> LabelList
    [assoc ctor metadata "43 mtLL.LabelList"] .
  op _<=_ : Nat Nat -> Bool
    [metadata "19"] .
  op _<_ : Nat Nat -> Bool
    [metadata "18"] .
  op _@_ : EmptyMessageList EmptyMessageList -> EmptyMessageList
    [assoc ctor metadata "52 mt.EmptyMessageList"] .
  op _@_ : HasFetchMsgList HasFetchMsgList -> HasFetchMsgList
    [assoc ctor metadata "52 mt.EmptyMessageList"] .
  op _@_ : HasFetchMsgList NonFetchMsgList -> HasFetchMsgList
    [assoc ctor metadata "52 mt.EmptyMessageList"] .
  op _@_ : MessageList MessageList -> MessageList
    [assoc ctor metadata "52 mt.EmptyMessageList"] .
  op _@_ : NonFetchMsgList HasFetchMsgList -> HasFetchMsgList
    [assoc ctor metadata "52 mt.EmptyMessageList"] .
  op _@_ : NonFetchMsgList NonFetchMsgList -> NonFetchMsgList
    [assoc ctor metadata "52 mt.EmptyMessageList"] .
  op __ : Configuration Configuration -> Configuration
    [assoc comm id:(none).EmptyConfiguration ctor metadata "35"] .
  op __ : EmptyConfiguration EmptyConfiguration -> EmptyConfiguration
    [assoc comm id:(none).EmptyConfiguration ctor metadata "35"] .
  op __ : NeConfiguration Configuration -> NeConfiguration
    [assoc comm id:(none).EmptyConfiguration ctor metadata "35"] .
  op __ : NetWebProcConfig NetWebProcConfig -> NetWebProcConfig
    [assoc comm id:(none).EmptyConfiguration ctor metadata "35"] .
  op __ : NetWebProcNeConfig NetWebProcConfig -> NetWebProcNeConfig
    [assoc comm id:(none).EmptyConfiguration ctor metadata "35"] .
  op _`,_ : AttributeSet AttributeSet -> AttributeSet
    [assoc comm id:(none).EmptyAttributeSet ctor metadata "34"] .
  op _`,_ : AttributeSet NeAttributeSet -> NeAttributeSet
    [assoc comm id:(none).EmptyAttributeSet ctor metadata "34"] .
  op _`,_ : EmptyAttributeSet EmptyAttributeSet -> EmptyAttributeSet
    [assoc comm id:(none).EmptyAttributeSet ctor metadata "34"] .
  op _`,np_ : NeNetProcInfoSet NetProcInfoSet -> NeNetProcInfoSet
    [assoc comm id: mtNPIS ctor metadata "75"] .
  op _`,np_ : NetProcInfoSet NetProcInfoSet -> NetProcInfoSet
    [assoc comm id: mtNPIS ctor metadata "75"] .
  op _`,ps_ : PolicySet PolicySet -> PolicySet
    [assoc comm id: mtPS ctor metadata "66"] .
  op _`,wp_ : NeWebProcInfoSet WebProcInfoSet -> NeWebProcInfoSet
    [assoc comm id: mtWPIS ctor metadata "72"] .
  op _`,wp_ : WebProcInfoSet WebProcInfoSet -> WebProcInfoSet
    [assoc comm id: mtWPIS ctor metadata "72"] .
  op _and_ : Bool Bool -> Bool
    [assoc comm prec 50 metadata "12"] .
  op _or_ : Bool Bool -> Bool
    [assoc comm metadata "13"] .
  op _~a_ : Attribute Attribute -> Bool
    [comm metadata "101"] .
  op _~l_ : Label Label -> Bool
    [comm metadata "42"] .
  op _~m_ : MsgType MsgType -> Bool
    [comm metadata "51"] .
  op _~n_ : Nat Nat -> Bool
    [comm metadata "22"] .
  op _~p_ : AbsProcessId AbsProcessId -> Bool
    [comm metadata "32"] .
  op `[_`] : Configuration -> State
    [ctor metadata "86"] .
  op `{_`} : Configuration -> State
    [ctor metadata "36"] .
  op about-blank : -> Label
    [ctor metadata "37"] .
  op activeWebapp : WebProcId -> Attribute
    [ctor metadata "78"] .
  op attr-dupl? : AttributeSet -> Bool
    [metadata "103"] .
  op attr-subset?`(_|_`) : AttributeSet AttributeSet -> Bool
    [metadata "104"] .
  op conf-attr-dupl!? : Configuration -> Bool
    [metadata "111"] .
  op conf-attr-dupl? : Configuration -> Bool
    [metadata "110"] .
  op conf-dupl? : Configuration -> Bool
    [metadata "107"] .
  op display : -> DisplayId
    [ctor metadata "29"] .
  op displayedContent : Label -> Attribute
    [ctor metadata "79"] .
  op displayedTopBar : Label -> Attribute
    [ctor metadata "77"] .
  op false : -> Bool
    [ctor special(id-hook SystemFalse)metadata "11"] .
  op fresh-netlabel? : Nat NetProcInfoSet -> Bool
    [metadata "126"] .
  op fresh-np-id? : NetProcId Configuration -> Bool
    [metadata "108"] .
  op fresh-weblabel? : Nat WebProcInfoSet -> Bool
    [metadata "125"] .
  op fresh-wp-id? : WebProcId Configuration -> Bool
    [metadata "109"] .
  op fromKernel : MessageList -> Attribute
    [ctor metadata "53"] .
  op handledCurrently : Message? -> Attribute
    [ctor metadata "70"] .
  op in : LabelList -> Attribute
    [ctor metadata "60"] .
  op in-attrset?`(_|_`) : Attribute AttributeSet -> Bool
    [metadata "102"] .
  op in-conf? : ProcessId Configuration -> Bool
    [metadata "106"] .
  op inlbl-by-pid : NetProcId NetProcInfoSet -> MaybeLabel
    [metadata "117"] .
  op inlbl-in-netlabels? : Label NetProcInfoSet -> Bool
    [metadata "128"] .
  op kernel : -> KernelId
    [ctor metadata "23"] .
  op lbl-in-weblabels? : Label WebProcInfoSet -> Bool
    [metadata "127"] .
  op loading : Bool -> Attribute
    [ctor metadata "58"] .
  op matching-procs1? : NetProcId Label NetProcInfoSet -> Bool
    [metadata "82"] .
  op matching-procs? : ProcessId ProcessId WebProcInfoSet NetProcInfoSet -> Bool
    [metadata "83"] .
  op mem-in : MaybeLabel -> Attribute
    [ctor metadata "63"] .
  op mem-out : MaybeLabel -> Attribute
    [ctor metadata "62"] .
  op metadata-match? : Configuration WebProcInfoSet NetProcInfoSet -> Bool
    [metadata "129"] .
  op msg : AbsPipeId AbsPipeId FetchMsgType Label -> FetchMsg
    [ctor metadata "49"] .
  op msg : AbsPipeId AbsPipeId MsgType Label -> Message
    [ctor metadata "49"] .
  op msg : AbsPipeId AbsPipeId NonFetchMsgType Label -> NonFetchMsg
    [ctor metadata "49"] .
  op msg : AbsPipeId AbsPipeId NonRetFetchMsgType Label -> NonRetFetchMsg
    [ctor metadata "49"] .
  op msg : AbsPipeId AbsPipeId NonRetMsgType Label -> NonRetMsg
    [ctor metadata "49"] .
  op msg : AbsPipeId AbsPipeId RetMsgType Label -> RetMsg
    [ctor metadata "49"] .
  op msgPolicy : PolicySet -> Attribute
    [ctor metadata "67"] .
  op mt : -> EmptyMessageList
    [ctor metadata "5"] .
  op mt : -> MessageList
    [ctor metadata "5"] .
  op mtLL : -> LabelList
    [ctor metadata "3"] .
  op mtLS : -> LabelSet
    [ctor metadata "4"] .
  op mtNPIS : -> NetProcInfoSet
    [ctor metadata "8"] .
  op mtPS : -> PolicySet
    [ctor metadata "6"] .
  op mtWPIS : -> WebProcInfoSet
    [ctor metadata "7"] .
  op nat-in-netlabels? : Nat NetProcInfoSet -> Bool
    [metadata "119"] .
  op nat-in-weblabels? : Nat WebProcInfoSet -> Bool
    [metadata "120"] .
  op netlabels : NetProcInfoSet -> Attribute
    [ctor metadata "76"] .
  op netlabels-dupl? : NetProcInfoSet -> Bool
    [metadata "124"] .
  op netproc-in-conf? : Configuration -> Bool
    [metadata "114"] .
  op network : Nat -> NetProcId
    [ctor metadata "27"] .
  op network : -> AbsNetProcId
    [ctor metadata "26"] .
  op nextNPN : Nat -> Attribute
    [ctor metadata "69"] .
  op nextWPN : Nat -> Attribute
    [ctor metadata "55"] .
  op nic : -> NICId
    [ctor metadata "30"] .
  op nic-in : LabelList -> Attribute
    [ctor metadata "65"] .
  op nic-out : LabelSet -> Attribute
    [ctor metadata "64"] .
  op nolabel : -> MaybeLabel
    [ctor metadata "39"] .
  op none : -> EmptyAttributeSet
    [ctor metadata "1"] .
  op none : -> EmptyConfiguration
    [ctor metadata "2"] .
  op none : -> Message?
    [ctor metadata "50"] .
  op not_ : Bool -> Bool
    [metadata "14"] .
  op np-by-lbl? : Label NetProcInfoSet -> Bool
    [metadata "81"] .
  op nwp-reqattrs!? : NetWebProcConfig -> Bool
    [metadata "113"] .
  op nwp-reqattrs? : NetWebProcConfig -> Bool
    [metadata "112"] .
  op out : LabelList -> Attribute
    [ctor metadata "61"] .
  op outlbl-by-pid : NetProcId NetProcInfoSet -> MaybeLabel
    [metadata "118"] .
  op p : NetWebProcConfig WebProcInfoSet NetProcInfoSet Message? -> Bool?
    [metadata "200"] .
  op pi : WebProcId Label -> WebProcInfo
    [ctor metadata "71"] .
  op pi : NetProcId Label Label -> NetProcInfo
    [ctor metadata "74"] .
  op pid-in-netlabels? : AbsProcessId NetProcInfoSet -> Bool
    [metadata "121"] .
  op pid-in-weblabels? : AbsProcessId WebProcInfoSet -> Bool
    [metadata "122"] .
  op policy : AbsPipeId AbsPipeId MsgType -> Policy
    [ctor metadata "68"] .
  op rendered : Label -> Attribute
    [ctor metadata "56"] .
  op returnTo : PipeId -> Attribute
    [ctor metadata "59"] .
  op toKernel : MessageList -> Attribute
    [ctor metadata "54"] .
  op true : -> Bool
    [ctor special(id-hook SystemTrue)metadata "10"] .
  op tt : -> Pred
    [ctor metadata "9"] .
  op ui : -> UIId
    [ctor metadata "28"] .
  op url : Nat -> Label
    [ctor metadata "38"] .
  op webapp : Nat -> WebProcId
    [ctor metadata "25"] .
  op webapp : -> AbsWebProcId
    [ctor metadata "24"] .
  op webappmgr : -> WebProcMgrId
    [ctor metadata "31"] .
  op weblabels : WebProcInfoSet -> Attribute
    [ctor metadata "73"] .
  op weblabels-dupl? : WebProcInfoSet -> Bool
    [metadata "123"] .
  op webproc-url-in-conf? : Configuration -> Bool
    [metadata "115"] .
  op webproc-url-netproc-in-conf? : Configuration -> Bool
    [metadata "116"] .
  eq none !a
    = (none).EmptyAttributeSet .
  eq (AS:AttributeSet,URL(X:Label))!a
    = URL(about-blank),AS:AttributeSet !a .
  eq (AS:AttributeSet,activeWebapp(X:WebProcId))!a
    = AS:AttributeSet !a,activeWebapp(webapp(0)) .
  eq (AS:AttributeSet,displayedContent(X:Label))!a
    = AS:AttributeSet !a,displayedContent(about-blank) .
  eq (AS:AttributeSet,displayedTopBar(X:Label))!a
    = AS:AttributeSet !a,displayedTopBar(about-blank) .
  eq (AS:AttributeSet,fromKernel(X:MessageList))!a
    = AS:AttributeSet !a,fromKernel(mt) .
  eq (AS:AttributeSet,handledCurrently(X:Message?))!a
    = AS:AttributeSet !a,handledCurrently(none) .
  eq (AS:AttributeSet,in(X:LabelList))!a
    = AS:AttributeSet !a,in(mtLL) .
  eq (AS:AttributeSet,loading(X:Bool))!a
    = AS:AttributeSet !a,loading(true) .
  eq (AS:AttributeSet,mem-in(X:MaybeLabel))!a
    = AS:AttributeSet !a,mem-in(nolabel) .
  eq (AS:AttributeSet,mem-out(X:MaybeLabel))!a
    = AS:AttributeSet !a,mem-out(nolabel) .
  eq (AS:AttributeSet,msgPolicy(X:PolicySet))!a
    = AS:AttributeSet !a,msgPolicy(mtPS) .
  eq (AS:AttributeSet,netlabels(X:NetProcInfoSet))!a
    = AS:AttributeSet !a,netlabels(mtNPIS) .
  eq (AS:AttributeSet,nextNPN(X:Nat))!a
    = AS:AttributeSet !a,nextNPN(0) .
  eq (AS:AttributeSet,nextWPN(X:Nat))!a
    = AS:AttributeSet !a,nextWPN(0) .
  eq (AS:AttributeSet,nic-in(X:LabelList))!a
    = AS:AttributeSet !a,nic-in(mtLL) .
  eq (AS:AttributeSet,nic-out(X:LabelSet))!a
    = AS:AttributeSet !a,nic-out(mtLS) .
  eq (AS:AttributeSet,out(X:LabelList))!a
    = AS:AttributeSet !a,out(mtLL) .
  eq (AS:AttributeSet,rendered(X:Label))!a
    = AS:AttributeSet !a,rendered(about-blank) .
  eq (AS:AttributeSet,returnTo(X:PipeId))!a
    = AS:AttributeSet !a,returnTo(ui) .
  eq (AS:AttributeSet,toKernel(X:MessageList))!a
    = AS:AttributeSet !a,toKernel(mt) .
  eq (AS:AttributeSet,weblabels(X:WebProcInfoSet))!a
    = AS:AttributeSet !a,weblabels(mtWPIS) .
  eq none !c
    = (none).EmptyConfiguration .
  eq (C:Configuration < PI:ProcessId | A:AttributeSet >)!c
    = C:Configuration !c < PI:ProcessId | A:AttributeSet !a > .
  eq URL(X:Label)~a URL(Y:Label)
    = true .
  eq URL(X:Label)~a activeWebapp(Y:WebProcId)
    = false .
  eq URL(X:Label)~a displayedContent(Y:Label)
    = false .
  eq URL(X:Label)~a displayedTopBar(Y:Label)
    = false .
  eq URL(X:Label)~a handledCurrently(Y:Message?)
    = false .
  eq URL(X:Label)~a in(Y:LabelList)
    = false .
  eq URL(X:Label)~a loading(Y:Bool)
    = false .
  eq URL(X:Label)~a mem-in(Y:MaybeLabel)
    = false .
  eq URL(X:Label)~a mem-out(Y:MaybeLabel)
    = false .
  eq URL(X:Label)~a msgPolicy(Y:PolicySet)
    = false .
  eq URL(X:Label)~a netlabels(Y:NetProcInfoSet)
    = false .
  eq URL(X:Label)~a nextNPN(Y:Nat)
    = false .
  eq URL(X:Label)~a nic-in(Y:LabelList)
    = false .
  eq URL(X:Label)~a nic-out(Y:LabelSet)
    = false .
  eq URL(X:Label)~a out(Y:LabelList)
    = false .
  eq URL(X:Label)~a returnTo(Y:PipeId)
    = false .
  eq URL(X:Label)~a weblabels(Y:WebProcInfoSet)
    = false .
  eq URL(Y:Label)~a fromKernel(X:MessageList)
    = false .
  eq URL(Y:Label)~a nextWPN(X:Nat)
    = false .
  eq URL(Y:Label)~a rendered(X:Label)
    = false .
  eq URL(Y:Label)~a toKernel(X:MessageList)
    = false .
  eq activeWebapp(X:WebProcId)~a activeWebapp(Y:WebProcId)
    = true .
  eq activeWebapp(Y:WebProcId)~a displayedContent(X:Label)
    = false .
  eq activeWebapp(Y:WebProcId)~a displayedTopBar(X:Label)
    = false .
  eq activeWebapp(Y:WebProcId)~a fromKernel(X:MessageList)
    = false .
  eq activeWebapp(Y:WebProcId)~a handledCurrently(X:Message?)
    = false .
  eq activeWebapp(Y:WebProcId)~a in(X:LabelList)
    = false .
  eq activeWebapp(Y:WebProcId)~a loading(X:Bool)
    = false .
  eq activeWebapp(Y:WebProcId)~a mem-in(X:MaybeLabel)
    = false .
  eq activeWebapp(Y:WebProcId)~a mem-out(X:MaybeLabel)
    = false .
  eq activeWebapp(Y:WebProcId)~a msgPolicy(X:PolicySet)
    = false .
  eq activeWebapp(Y:WebProcId)~a netlabels(X:NetProcInfoSet)
    = false .
  eq activeWebapp(Y:WebProcId)~a nextNPN(X:Nat)
    = false .
  eq activeWebapp(Y:WebProcId)~a nextWPN(X:Nat)
    = false .
  eq activeWebapp(Y:WebProcId)~a nic-in(X:LabelList)
    = false .
  eq activeWebapp(Y:WebProcId)~a nic-out(X:LabelSet)
    = false .
  eq activeWebapp(Y:WebProcId)~a out(X:LabelList)
    = false .
  eq activeWebapp(Y:WebProcId)~a rendered(X:Label)
    = false .
  eq activeWebapp(Y:WebProcId)~a returnTo(X:PipeId)
    = false .
  eq activeWebapp(Y:WebProcId)~a toKernel(X:MessageList)
    = false .
  eq activeWebapp(Y:WebProcId)~a weblabels(X:WebProcInfoSet)
    = false .
  eq displayedContent(X:Label)~a displayedContent(Y:Label)
    = true .
  eq displayedContent(Y:Label)~a displayedTopBar(X:Label)
    = false .
  eq displayedContent(Y:Label)~a fromKernel(X:MessageList)
    = false .
  eq displayedContent(Y:Label)~a handledCurrently(X:Message?)
    = false .
  eq displayedContent(Y:Label)~a in(X:LabelList)
    = false .
  eq displayedContent(Y:Label)~a loading(X:Bool)
    = false .
  eq displayedContent(Y:Label)~a mem-in(X:MaybeLabel)
    = false .
  eq displayedContent(Y:Label)~a mem-out(X:MaybeLabel)
    = false .
  eq displayedContent(Y:Label)~a msgPolicy(X:PolicySet)
    = false .
  eq displayedContent(Y:Label)~a netlabels(X:NetProcInfoSet)
    = false .
  eq displayedContent(Y:Label)~a nextNPN(X:Nat)
    = false .
  eq displayedContent(Y:Label)~a nextWPN(X:Nat)
    = false .
  eq displayedContent(Y:Label)~a nic-in(X:LabelList)
    = false .
  eq displayedContent(Y:Label)~a nic-out(X:LabelSet)
    = false .
  eq displayedContent(Y:Label)~a out(X:LabelList)
    = false .
  eq displayedContent(Y:Label)~a rendered(X:Label)
    = false .
  eq displayedContent(Y:Label)~a returnTo(X:PipeId)
    = false .
  eq displayedContent(Y:Label)~a toKernel(X:MessageList)
    = false .
  eq displayedContent(Y:Label)~a weblabels(X:WebProcInfoSet)
    = false .
  eq displayedTopBar(X:Label)~a displayedTopBar(Y:Label)
    = true .
  eq displayedTopBar(Y:Label)~a fromKernel(X:MessageList)
    = false .
  eq displayedTopBar(Y:Label)~a handledCurrently(X:Message?)
    = false .
  eq displayedTopBar(Y:Label)~a in(X:LabelList)
    = false .
  eq displayedTopBar(Y:Label)~a loading(X:Bool)
    = false .
  eq displayedTopBar(Y:Label)~a mem-in(X:MaybeLabel)
    = false .
  eq displayedTopBar(Y:Label)~a mem-out(X:MaybeLabel)
    = false .
  eq displayedTopBar(Y:Label)~a msgPolicy(X:PolicySet)
    = false .
  eq displayedTopBar(Y:Label)~a netlabels(X:NetProcInfoSet)
    = false .
  eq displayedTopBar(Y:Label)~a nextNPN(X:Nat)
    = false .
  eq displayedTopBar(Y:Label)~a nextWPN(X:Nat)
    = false .
  eq displayedTopBar(Y:Label)~a nic-in(X:LabelList)
    = false .
  eq displayedTopBar(Y:Label)~a nic-out(X:LabelSet)
    = false .
  eq displayedTopBar(Y:Label)~a out(X:LabelList)
    = false .
  eq displayedTopBar(Y:Label)~a rendered(X:Label)
    = false .
  eq displayedTopBar(Y:Label)~a returnTo(X:PipeId)
    = false .
  eq displayedTopBar(Y:Label)~a toKernel(X:MessageList)
    = false .
  eq displayedTopBar(Y:Label)~a weblabels(X:WebProcInfoSet)
    = false .
  eq fromKernel(X:MessageList)~a fromKernel(Y:MessageList)
    = true .
  eq fromKernel(X:MessageList)~a handledCurrently(Y:Message?)
    = false .
  eq fromKernel(X:MessageList)~a in(Y:LabelList)
    = false .
  eq fromKernel(X:MessageList)~a loading(Y:Bool)
    = false .
  eq fromKernel(X:MessageList)~a mem-in(Y:MaybeLabel)
    = false .
  eq fromKernel(X:MessageList)~a mem-out(Y:MaybeLabel)
    = false .
  eq fromKernel(X:MessageList)~a msgPolicy(Y:PolicySet)
    = false .
  eq fromKernel(X:MessageList)~a netlabels(Y:NetProcInfoSet)
    = false .
  eq fromKernel(X:MessageList)~a nextNPN(Y:Nat)
    = false .
  eq fromKernel(X:MessageList)~a nextWPN(Y:Nat)
    = false .
  eq fromKernel(X:MessageList)~a nic-in(Y:LabelList)
    = false .
  eq fromKernel(X:MessageList)~a nic-out(Y:LabelSet)
    = false .
  eq fromKernel(X:MessageList)~a out(Y:LabelList)
    = false .
  eq fromKernel(X:MessageList)~a rendered(Y:Label)
    = false .
  eq fromKernel(X:MessageList)~a returnTo(Y:PipeId)
    = false .
  eq fromKernel(X:MessageList)~a toKernel(Y:MessageList)
    = false .
  eq fromKernel(X:MessageList)~a weblabels(Y:WebProcInfoSet)
    = false .
  eq handledCurrently(X:Message?)~a handledCurrently(Y:Message?)
    = true .
  eq handledCurrently(X:Message?)~a netlabels(Y:NetProcInfoSet)
    = false .
  eq handledCurrently(X:Message?)~a weblabels(Y:WebProcInfoSet)
    = false .
  eq handledCurrently(Y:Message?)~a in(X:LabelList)
    = false .
  eq handledCurrently(Y:Message?)~a loading(X:Bool)
    = false .
  eq handledCurrently(Y:Message?)~a mem-in(X:MaybeLabel)
    = false .
  eq handledCurrently(Y:Message?)~a mem-out(X:MaybeLabel)
    = false .
  eq handledCurrently(Y:Message?)~a msgPolicy(X:PolicySet)
    = false .
  eq handledCurrently(Y:Message?)~a nextNPN(X:Nat)
    = false .
  eq handledCurrently(Y:Message?)~a nextWPN(X:Nat)
    = false .
  eq handledCurrently(Y:Message?)~a nic-in(X:LabelList)
    = false .
  eq handledCurrently(Y:Message?)~a nic-out(X:LabelSet)
    = false .
  eq handledCurrently(Y:Message?)~a out(X:LabelList)
    = false .
  eq handledCurrently(Y:Message?)~a rendered(X:Label)
    = false .
  eq handledCurrently(Y:Message?)~a returnTo(X:PipeId)
    = false .
  eq handledCurrently(Y:Message?)~a toKernel(X:MessageList)
    = false .
  eq in(X:LabelList)~a in(Y:LabelList)
    = true .
  eq in(X:LabelList)~a mem-in(Y:MaybeLabel)
    = false .
  eq in(X:LabelList)~a mem-out(Y:MaybeLabel)
    = false .
  eq in(X:LabelList)~a msgPolicy(Y:PolicySet)
    = false .
  eq in(X:LabelList)~a netlabels(Y:NetProcInfoSet)
    = false .
  eq in(X:LabelList)~a nextNPN(Y:Nat)
    = false .
  eq in(X:LabelList)~a nic-in(Y:LabelList)
    = false .
  eq in(X:LabelList)~a nic-out(Y:LabelSet)
    = false .
  eq in(X:LabelList)~a out(Y:LabelList)
    = false .
  eq in(X:LabelList)~a weblabels(Y:WebProcInfoSet)
    = false .
  eq in(Y:LabelList)~a loading(X:Bool)
    = false .
  eq in(Y:LabelList)~a nextWPN(X:Nat)
    = false .
  eq in(Y:LabelList)~a rendered(X:Label)
    = false .
  eq in(Y:LabelList)~a returnTo(X:PipeId)
    = false .
  eq in(Y:LabelList)~a toKernel(X:MessageList)
    = false .
  eq loading(X:Bool)~a loading(Y:Bool)
    = true .
  eq loading(X:Bool)~a mem-in(Y:MaybeLabel)
    = false .
  eq loading(X:Bool)~a mem-out(Y:MaybeLabel)
    = false .
  eq loading(X:Bool)~a msgPolicy(Y:PolicySet)
    = false .
  eq loading(X:Bool)~a netlabels(Y:NetProcInfoSet)
    = false .
  eq loading(X:Bool)~a nextNPN(Y:Nat)
    = false .
  eq loading(X:Bool)~a nic-in(Y:LabelList)
    = false .
  eq loading(X:Bool)~a nic-out(Y:LabelSet)
    = false .
  eq loading(X:Bool)~a out(Y:LabelList)
    = false .
  eq loading(X:Bool)~a returnTo(Y:PipeId)
    = false .
  eq loading(X:Bool)~a weblabels(Y:WebProcInfoSet)
    = false .
  eq loading(Y:Bool)~a nextWPN(X:Nat)
    = false .
  eq loading(Y:Bool)~a rendered(X:Label)
    = false .
  eq loading(Y:Bool)~a toKernel(X:MessageList)
    = false .
  eq mem-in(X:MaybeLabel)~a mem-in(Y:MaybeLabel)
    = true .
  eq mem-in(X:MaybeLabel)~a mem-out(Y:MaybeLabel)
    = false .
  eq mem-in(X:MaybeLabel)~a msgPolicy(Y:PolicySet)
    = false .
  eq mem-in(X:MaybeLabel)~a netlabels(Y:NetProcInfoSet)
    = false .
  eq mem-in(X:MaybeLabel)~a nextNPN(Y:Nat)
    = false .
  eq mem-in(X:MaybeLabel)~a nic-in(Y:LabelList)
    = false .
  eq mem-in(X:MaybeLabel)~a nic-out(Y:LabelSet)
    = false .
  eq mem-in(X:MaybeLabel)~a weblabels(Y:WebProcInfoSet)
    = false .
  eq mem-in(Y:MaybeLabel)~a nextWPN(X:Nat)
    = false .
  eq mem-in(Y:MaybeLabel)~a out(X:LabelList)
    = false .
  eq mem-in(Y:MaybeLabel)~a rendered(X:Label)
    = false .
  eq mem-in(Y:MaybeLabel)~a returnTo(X:PipeId)
    = false .
  eq mem-in(Y:MaybeLabel)~a toKernel(X:MessageList)
    = false .
  eq mem-out(X:MaybeLabel)~a mem-out(Y:MaybeLabel)
    = true .
  eq mem-out(X:MaybeLabel)~a msgPolicy(Y:PolicySet)
    = false .
  eq mem-out(X:MaybeLabel)~a netlabels(Y:NetProcInfoSet)
    = false .
  eq mem-out(X:MaybeLabel)~a nextNPN(Y:Nat)
    = false .
  eq mem-out(X:MaybeLabel)~a nic-in(Y:LabelList)
    = false .
  eq mem-out(X:MaybeLabel)~a nic-out(Y:LabelSet)
    = false .
  eq mem-out(X:MaybeLabel)~a weblabels(Y:WebProcInfoSet)
    = false .
  eq mem-out(Y:MaybeLabel)~a nextWPN(X:Nat)
    = false .
  eq mem-out(Y:MaybeLabel)~a out(X:LabelList)
    = false .
  eq mem-out(Y:MaybeLabel)~a rendered(X:Label)
    = false .
  eq mem-out(Y:MaybeLabel)~a returnTo(X:PipeId)
    = false .
  eq mem-out(Y:MaybeLabel)~a toKernel(X:MessageList)
    = false .
  eq msgPolicy(X:PolicySet)~a msgPolicy(Y:PolicySet)
    = true .
  eq msgPolicy(X:PolicySet)~a netlabels(Y:NetProcInfoSet)
    = false .
  eq msgPolicy(X:PolicySet)~a nextNPN(Y:Nat)
    = false .
  eq msgPolicy(X:PolicySet)~a weblabels(Y:WebProcInfoSet)
    = false .
  eq msgPolicy(Y:PolicySet)~a nextWPN(X:Nat)
    = false .
  eq msgPolicy(Y:PolicySet)~a nic-in(X:LabelList)
    = false .
  eq msgPolicy(Y:PolicySet)~a nic-out(X:LabelSet)
    = false .
  eq msgPolicy(Y:PolicySet)~a out(X:LabelList)
    = false .
  eq msgPolicy(Y:PolicySet)~a rendered(X:Label)
    = false .
  eq msgPolicy(Y:PolicySet)~a returnTo(X:PipeId)
    = false .
  eq msgPolicy(Y:PolicySet)~a toKernel(X:MessageList)
    = false .
  eq netlabels(X:NetProcInfoSet)~a netlabels(Y:NetProcInfoSet)
    = true .
  eq netlabels(Y:NetProcInfoSet)~a nextNPN(X:Nat)
    = false .
  eq netlabels(Y:NetProcInfoSet)~a nextWPN(X:Nat)
    = false .
  eq netlabels(Y:NetProcInfoSet)~a nic-in(X:LabelList)
    = false .
  eq netlabels(Y:NetProcInfoSet)~a nic-out(X:LabelSet)
    = false .
  eq netlabels(Y:NetProcInfoSet)~a out(X:LabelList)
    = false .
  eq netlabels(Y:NetProcInfoSet)~a rendered(X:Label)
    = false .
  eq netlabels(Y:NetProcInfoSet)~a returnTo(X:PipeId)
    = false .
  eq netlabels(Y:NetProcInfoSet)~a toKernel(X:MessageList)
    = false .
  eq netlabels(Y:NetProcInfoSet)~a weblabels(X:WebProcInfoSet)
    = false .
  eq nextNPN(X:Nat)~a nextNPN(Y:Nat)
    = true .
  eq nextNPN(X:Nat)~a weblabels(Y:WebProcInfoSet)
    = false .
  eq nextNPN(Y:Nat)~a nextWPN(X:Nat)
    = false .
  eq nextNPN(Y:Nat)~a nic-in(X:LabelList)
    = false .
  eq nextNPN(Y:Nat)~a nic-out(X:LabelSet)
    = false .
  eq nextNPN(Y:Nat)~a out(X:LabelList)
    = false .
  eq nextNPN(Y:Nat)~a rendered(X:Label)
    = false .
  eq nextNPN(Y:Nat)~a returnTo(X:PipeId)
    = false .
  eq nextNPN(Y:Nat)~a toKernel(X:MessageList)
    = false .
  eq nextWPN(X:Nat)~a nextWPN(Y:Nat)
    = true .
  eq nextWPN(X:Nat)~a nic-in(Y:LabelList)
    = false .
  eq nextWPN(X:Nat)~a nic-out(Y:LabelSet)
    = false .
  eq nextWPN(X:Nat)~a out(Y:LabelList)
    = false .
  eq nextWPN(X:Nat)~a rendered(Y:Label)
    = false .
  eq nextWPN(X:Nat)~a returnTo(Y:PipeId)
    = false .
  eq nextWPN(X:Nat)~a weblabels(Y:WebProcInfoSet)
    = false .
  eq nextWPN(Y:Nat)~a toKernel(X:MessageList)
    = false .
  eq nic-in(X:LabelList)~a nic-in(Y:LabelList)
    = true .
  eq nic-in(X:LabelList)~a nic-out(Y:LabelSet)
    = false .
  eq nic-in(X:LabelList)~a weblabels(Y:WebProcInfoSet)
    = false .
  eq nic-in(Y:LabelList)~a out(X:LabelList)
    = false .
  eq nic-in(Y:LabelList)~a rendered(X:Label)
    = false .
  eq nic-in(Y:LabelList)~a returnTo(X:PipeId)
    = false .
  eq nic-in(Y:LabelList)~a toKernel(X:MessageList)
    = false .
  eq nic-out(X:LabelSet)~a nic-out(Y:LabelSet)
    = true .
  eq nic-out(X:LabelSet)~a weblabels(Y:WebProcInfoSet)
    = false .
  eq nic-out(Y:LabelSet)~a out(X:LabelList)
    = false .
  eq nic-out(Y:LabelSet)~a rendered(X:Label)
    = false .
  eq nic-out(Y:LabelSet)~a returnTo(X:PipeId)
    = false .
  eq nic-out(Y:LabelSet)~a toKernel(X:MessageList)
    = false .
  eq out(X:LabelList)~a out(Y:LabelList)
    = true .
  eq out(X:LabelList)~a weblabels(Y:WebProcInfoSet)
    = false .
  eq out(Y:LabelList)~a rendered(X:Label)
    = false .
  eq out(Y:LabelList)~a returnTo(X:PipeId)
    = false .
  eq out(Y:LabelList)~a toKernel(X:MessageList)
    = false .
  eq rendered(X:Label)~a rendered(Y:Label)
    = true .
  eq rendered(X:Label)~a returnTo(Y:PipeId)
    = false .
  eq rendered(X:Label)~a weblabels(Y:WebProcInfoSet)
    = false .
  eq rendered(Y:Label)~a toKernel(X:MessageList)
    = false .
  eq returnTo(X:PipeId)~a returnTo(Y:PipeId)
    = true .
  eq returnTo(X:PipeId)~a weblabels(Y:WebProcInfoSet)
    = false .
  eq returnTo(Y:PipeId)~a toKernel(X:MessageList)
    = false .
  eq toKernel(X:MessageList)~a toKernel(Y:MessageList)
    = true .
  eq toKernel(X:MessageList)~a weblabels(Y:WebProcInfoSet)
    = false .
  eq weblabels(X:WebProcInfoSet)~a weblabels(Y:WebProcInfoSet)
    = true .
  eq MSG-FETCH-URL ~m M:NonFetchMsgType
    = false .
  eq MSG-FETCH-URL ~m MSG-NEW-URL
    = false .
  eq MSG-FETCH-URL ~m MSG-SWITCH-TAB
    = false .
  eq MSG-NEW-URL ~m MSG-SWITCH-TAB
    = false .
  eq MSG-RETURN-URL ~m M:NonRetMsgType
    = false .
  eq MSG-RETURN-URL ~m MSG-SWITCH-TAB
    = false .
  eq X:MsgType ~m X:MsgType
    = true .
  eq attr-dupl?(A:Attribute)
    = false .
  eq attr-dupl?(AS:AttributeSet,URL(X:Label),URL(Y:Label))
    = true .
  eq attr-dupl?(AS:AttributeSet,activeWebapp(X:WebProcId),activeWebapp(Y:WebProcId))
    = true .
  eq attr-dupl?(AS:AttributeSet,displayedContent(X:Label),displayedContent(Y:Label))
    = true .
  eq attr-dupl?(AS:AttributeSet,displayedTopBar(X:Label),displayedTopBar(Y:Label))
    = true .
  eq attr-dupl?(AS:AttributeSet,fromKernel(X:MessageList),fromKernel(Y:MessageList))
    = true .
  eq attr-dupl?(AS:AttributeSet,handledCurrently(X:Message?),handledCurrently(Y:Message?))
    = true .
  eq attr-dupl?(AS:AttributeSet,in(X:LabelList),in(Y:LabelList))
    = true .
  eq attr-dupl?(AS:AttributeSet,loading(X:Bool),loading(Y:Bool))
    = true .
  eq attr-dupl?(AS:AttributeSet,mem-in(X:MaybeLabel),mem-in(Y:MaybeLabel))
    = true .
  eq attr-dupl?(AS:AttributeSet,mem-out(X:MaybeLabel),mem-out(Y:MaybeLabel))
    = true .
  eq attr-dupl?(AS:AttributeSet,msgPolicy(X:PolicySet),msgPolicy(Y:PolicySet))
    = true .
  eq attr-dupl?(AS:AttributeSet,netlabels(X:NetProcInfoSet),netlabels(Y:NetProcInfoSet))
    = true .
  eq attr-dupl?(AS:AttributeSet,nextNPN(X:Nat),nextNPN(Y:Nat))
    = true .
  eq attr-dupl?(AS:AttributeSet,nextWPN(X:Nat),nextWPN(Y:Nat))
    = true .
  eq attr-dupl?(AS:AttributeSet,nic-in(X:LabelList),nic-in(Y:LabelList))
    = true .
  eq attr-dupl?(AS:AttributeSet,nic-out(X:LabelSet),nic-out(Y:LabelSet))
    = true .
  eq attr-dupl?(AS:AttributeSet,out(X:LabelList),out(Y:LabelList))
    = true .
  eq attr-dupl?(AS:AttributeSet,rendered(X:Label),rendered(Y:Label))
    = true .
  eq attr-dupl?(AS:AttributeSet,returnTo(X:PipeId),returnTo(Y:PipeId))
    = true .
  eq attr-dupl?(AS:AttributeSet,toKernel(X:MessageList),toKernel(Y:MessageList))
    = true .
  eq attr-dupl?(AS:AttributeSet,weblabels(X:WebProcInfoSet),weblabels(Y:WebProcInfoSet))
    = true .
  eq attr-subset?(none | AS':AttributeSet)
    = true .
  eq conf-attr-dupl!?(C:Configuration)
    = conf-attr-dupl?(C:Configuration !c) .
  eq conf-attr-dupl?(none)
    = false .
  eq conf-attr-dupl?(C:Configuration < PI:ProcessId | At:Attribute >)
    = conf-attr-dupl?(C:Configuration) .
  eq conf-attr-dupl?(C:Configuration < PI:ProcessId | none >)
    = conf-attr-dupl?(C:Configuration) .
  eq conf-dupl?(none)
    = false .
  eq conf-dupl?(C:Configuration < PI:ProcessId | NA:NeAttributeSet >)
    = conf-dupl?(C:Configuration < PI:ProcessId | none >) .
  eq conf-dupl?(C:Configuration < PI:ProcessId | A:AttributeSet > < PI:ProcessId | A':AttributeSet >)
    = true .
  eq fresh-netlabel?(N:Nat,mtNPIS)
    = true .
  eq fresh-netlabel?(N:Nat,NIS:NetProcInfoSet,np pi(network(N:Nat + M:Nat),L:Label,L':Label))
    = false .
  eq fresh-netlabel?(N:Nat + P:NzNat,NIS:NetProcInfoSet,np pi(network(N:Nat),L:Label,L':Label))
    = fresh-netlabel?(N:Nat + P:NzNat,NIS:NetProcInfoSet) .
  eq fresh-np-id?(network(M:Nat),C:Configuration < NPI:NetProcId | NA:NeAttributeSet >)
    = fresh-np-id?(network(M:Nat),C:Configuration < NPI:NetProcId | none >) .
  eq fresh-np-id?(network(N:Nat),none)
    = true .
  eq fresh-np-id?(network(N:Nat),C:Configuration < NNPI:NonNetProcId | A:AttributeSet >)
    = fresh-np-id?(network(N:Nat),C:Configuration) .
  eq fresh-np-id?(network(N:Nat),C:Configuration < network | A:AttributeSet >)
    = fresh-np-id?(network(N:Nat),C:Configuration) .
  eq fresh-np-id?(network(N:Nat),C:Configuration < network(N:Nat + M:Nat)| A:AttributeSet >)
    = false .
  eq fresh-np-id?(network(N:Nat + P:NzNat),C:Configuration < network(N:Nat)| A:AttributeSet >)
    = fresh-np-id?(network(N:Nat + P:NzNat),C:Configuration) .
  eq fresh-weblabel?(N:Nat,mtWPIS)
    = true .
  eq fresh-weblabel?(N:Nat,WIS:WebProcInfoSet,wp pi(network(N:Nat + M:Nat),L:Label))
    = false .
  eq fresh-weblabel?(N:Nat + P:NzNat,WIS:WebProcInfoSet,wp pi(network(N:Nat),L:Label))
    = fresh-weblabel?(N:Nat + P:NzNat,WIS:WebProcInfoSet) .
  eq fresh-wp-id?(webapp(M:Nat),C:Configuration < WAI:WebProcId | NA:NeAttributeSet >)
    = fresh-wp-id?(webapp(M:Nat),C:Configuration < WAI:WebProcId | none >) .
  eq fresh-wp-id?(webapp(N:Nat),none)
    = true .
  eq fresh-wp-id?(webapp(N:Nat),C:Configuration < NWAI:NonWebProcId | A:AttributeSet >)
    = fresh-wp-id?(webapp(N:Nat),C:Configuration) .
  eq fresh-wp-id?(webapp(N:Nat),C:Configuration < webapp | A:AttributeSet >)
    = fresh-wp-id?(webapp(N:Nat),C:Configuration) .
  eq fresh-wp-id?(webapp(N:Nat),C:Configuration < webapp(N:Nat + M:Nat)| A:AttributeSet >)
    = false .
  eq fresh-wp-id?(webapp(N:Nat + P:NzNat),C:Configuration < webapp(N:Nat)| A:AttributeSet >)
    = fresh-wp-id?(webapp(N:Nat + P:NzNat),C:Configuration) .
  eq in-attrset?(A:Attribute | none)
    = false .
  eq in-attrset?(URL(X:Label)| AS:AttributeSet,URL(Y:Label))
    = true .
  eq in-attrset?(activeWebapp(X:WebProcId)| AS:AttributeSet,activeWebapp(Y:WebProcId))
    = true .
  eq in-attrset?(displayedContent(X:Label)| AS:AttributeSet,displayedContent(Y:Label))
    = true .
  eq in-attrset?(displayedTopBar(X:Label)| AS:AttributeSet,displayedTopBar(Y:Label))
    = true .
  eq in-attrset?(fromKernel(X:MessageList)| AS:AttributeSet,fromKernel(Y:MessageList))
    = true .
  eq in-attrset?(handledCurrently(X:Message?)| AS:AttributeSet,handledCurrently(Y:Message?))
    = true .
  eq in-attrset?(in(X:LabelList)| AS:AttributeSet,in(Y:LabelList))
    = true .
  eq in-attrset?(loading(X:Bool)| AS:AttributeSet,loading(Y:Bool))
    = true .
  eq in-attrset?(mem-in(X:MaybeLabel)| AS:AttributeSet,mem-in(Y:MaybeLabel))
    = true .
  eq in-attrset?(mem-out(X:MaybeLabel)| AS:AttributeSet,mem-out(Y:MaybeLabel))
    = true .
  eq in-attrset?(msgPolicy(X:PolicySet)| AS:AttributeSet,msgPolicy(Y:PolicySet))
    = true .
  eq in-attrset?(netlabels(X:NetProcInfoSet)| AS:AttributeSet,netlabels(Y:NetProcInfoSet))
    = true .
  eq in-attrset?(nextNPN(X:Nat)| AS:AttributeSet,nextNPN(Y:Nat))
    = true .
  eq in-attrset?(nextWPN(X:Nat)| AS:AttributeSet,nextWPN(Y:Nat))
    = true .
  eq in-attrset?(nic-in(X:LabelList)| AS:AttributeSet,nic-in(Y:LabelList))
    = true .
  eq in-attrset?(nic-out(X:LabelSet)| AS:AttributeSet,nic-out(Y:LabelSet))
    = true .
  eq in-attrset?(out(X:LabelList)| AS:AttributeSet,out(Y:LabelList))
    = true .
  eq in-attrset?(rendered(X:Label)| AS:AttributeSet,rendered(Y:Label))
    = true .
  eq in-attrset?(returnTo(X:PipeId)| AS:AttributeSet,returnTo(Y:PipeId))
    = true .
  eq in-attrset?(toKernel(X:MessageList)| AS:AttributeSet,toKernel(Y:MessageList))
    = true .
  eq in-attrset?(weblabels(X:WebProcInfoSet)| AS:AttributeSet,weblabels(Y:WebProcInfoSet))
    = true .
  eq in-conf?(PI:ProcessId,none)
    = false .
  eq in-conf?(PI:ProcessId,C:Configuration < PI:ProcessId | A':AttributeSet >)
    = true .
  eq inlbl-by-pid(NPI:NetProcId,mtNPIS)
    = nolabel .
  eq inlbl-by-pid(NPI:NetProcId,NIS:NetProcInfoSet,np pi(NPI:NetProcId,IN:Label,OUT:Label))
    = IN:Label .
  eq inlbl-in-netlabels?(IN:Label,NIS:NetProcInfoSet,np pi(NPI:NetProcId,IN:Label,OUT:Label))
    = true .
  eq inlbl-in-netlabels?(L:Label,mtNPIS)
    = false .
  eq lbl-in-weblabels?(L:Label,mtWPIS)
    = false .
  eq lbl-in-weblabels?(L:Label,WIS:WebProcInfoSet,wp pi(WAI:WebProcId,L:Label))
    = true .
  eq matching-procs1?(NI:NetProcId,L:Label,mtNPIS)
    = false .
  eq matching-procs1?(NI:NetProcId,L:Label,NPIS:NetProcInfoSet,np pi(NI:NetProcId,L:Label,L'':Label))
    = true .
  eq matching-procs?(NI:NetProcId,WI:WebProcId,WPIS:WebProcInfoSet,wp pi(WI:WebProcId,L:Label),NPIS:NetProcInfoSet)
    = matching-procs1?(NI:NetProcId,L:Label,NPIS:NetProcInfoSet)or matching-procs?(NI:NetProcId,WI:WebProcId,WPIS:WebProcInfoSet,NPIS:NetProcInfoSet) .
  eq matching-procs?(NPI:NonPipeId,NPI':NonPipeId,WPIS:WebProcInfoSet,NPIS:NetProcInfoSet)
    = false .
  eq matching-procs?(NPI:NonPipeId,UI:UIId,WPIS:WebProcInfoSet,NPIS:NetProcInfoSet)
    = false .
  eq matching-procs?(PI:ProcessId,PI':ProcessId,mtWPIS,NPIS:NetProcInfoSet)
    = false .
  eq matching-procs?(UI:UIId,NPI:NonPipeId,WPIS:WebProcInfoSet,NPIS:NetProcInfoSet)
    = false .
  eq matching-procs?(WI:WebProcId,NI:NetProcId,WPIS:WebProcInfoSet,NPIS:NetProcInfoSet)
    = false .
  eq metadata-match?(C:Configuration,mtWPIS,NNIS:NeNetProcInfoSet)
    = false .
  eq metadata-match?(none,mtWPIS,mtNPIS)
    = true .
  eq metadata-match?(C:Configuration < NonPID:NonPipeId | A:AttributeSet >,WIS:WebProcInfoSet,NIS:NetProcInfoSet)
    = metadata-match?(C:Configuration,WIS:WebProcInfoSet,NIS:NetProcInfoSet) .
  eq metadata-match?(C:Configuration < WAI:WebProcId | A:AttributeSet,URL(L:Label)>,WIS:WebProcInfoSet,wp pi(WAI:WebProcId,L:Label),mtNPIS)
    = metadata-match?(C:Configuration,WIS:WebProcInfoSet,mtNPIS) .
  eq metadata-match?(C:Configuration < ui | A:AttributeSet >,WIS:WebProcInfoSet,NIS:NetProcInfoSet)
    = metadata-match?(C:Configuration,WIS:WebProcInfoSet,NIS:NetProcInfoSet) .
  eq metadata-match?(C:Configuration < WAI:WebProcId | A:AttributeSet,URL(L:Label)> < NPI:NetProcId | A':AttributeSet >,WIS:WebProcInfoSet,wp pi(WAI:WebProcId,L:Label),NIS:NetProcInfoSet,np pi(NPI:NetProcId,L:Label,L':Label))
    = metadata-match?(C:Configuration,WIS:WebProcInfoSet,NIS:NetProcInfoSet) .
  eq nat-in-netlabels?(N:Nat,mtNPIS)
    = false .
  eq nat-in-weblabels?(N:Nat,mtWPIS)
    = false .
  eq netlabels-dupl?(mtNPIS)
    = false .
  eq netlabels-dupl?(NIS:NetProcInfoSet,np pi(NPI:NetProcId,L:Label,L':Label),np pi(NPI':NetProcId,L1:Label,L2:Label))
    = true .
  eq netlabels-dupl?(pi(NPI:NetProcId,L:Label,L':Label))
    = false .
  eq netproc-in-conf?(none)
    = false .
  eq netproc-in-conf?(C:Configuration < NNPI:NonNetProcId | A:AttributeSet >)
    = netproc-in-conf?(C:Configuration) .
  eq netproc-in-conf?(C:Configuration < NPI:NetProcId | A:AttributeSet >)
    = true .
  eq np-by-lbl?(L':Label,mtNPIS)
    = false .
  eq nwp-reqattrs!?(C:Configuration)
    = nwp-reqattrs?(C:Configuration !c) .
  eq nwp-reqattrs?(none)
    = true .
  eq nwp-reqattrs?(C:Configuration < NPI:NetProcId | A:AttributeSet,fromKernel(FK:MessageList),mem-in(M1:MaybeLabel),mem-out(M2:MaybeLabel),returnTo(P:PipeId),toKernel(TK:MessageList)>)
    = nwp-reqattrs?(C:Configuration) .
  eq nwp-reqattrs?(C:Configuration < WAI:WebProcId | A:AttributeSet,URL(L1:Label),fromKernel(FK:MessageList),loading(B:Bool),rendered(L2:Label),toKernel(TK:MessageList)>)
    = nwp-reqattrs?(C:Configuration) .
  eq outlbl-by-pid(NPI:NetProcId,mtNPIS)
    = nolabel .
  eq outlbl-by-pid(NPI:NetProcId,NIS:NetProcInfoSet,np pi(NPI:NetProcId,IN:Label,OUT:Label))
    = OUT:Label .
  eq p(NWC:NetWebProcConfig,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT:Label),msg(NI:NetProcId,WI:WebProcId,MT:MsgType,OUT:Label))
    = p(NWC:NetWebProcConfig,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT:Label),none) .
  eq p(NWC:NetWebProcConfig,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT:Label),msg(WI:WebProcId,NI:NetProcId,MT:MsgType,OUT:Label))
    = p(NWC:NetWebProcConfig,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT:Label),none) .
  eq p(none,mtWPIS,mtNPIS,none)
    = true .
  eq p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,fromKernel(NFM:NonFetchMsg)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,fromKernel(mt)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?) .
  eq p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,fromKernel(ML:MessageList @ NFM:NonFetchMsg)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,fromKernel(ML:MessageList)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?) .
  eq p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,fromKernel(NFM:NonFetchMsg @ ML2:MessageList)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,fromKernel(ML2:MessageList)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?) .
  eq p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,fromKernel(ML:MessageList @ NFM:NonFetchMsg @ ML2:MessageList)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,fromKernel(ML:MessageList @ ML2:MessageList)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?) .
  eq p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,toKernel(NRM:NonRetMsg)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,toKernel(mt)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?) .
  eq p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,toKernel(ML:MessageList @ NRM:NonRetMsg)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,toKernel(ML:MessageList)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?) .
  eq p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,toKernel(NRM:NonRetMsg @ ML2:MessageList)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,toKernel(ML2:MessageList)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?) .
  eq p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,toKernel(ML:MessageList @ NRM:NonRetMsg @ ML2:MessageList)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,toKernel(ML:MessageList @ ML2:MessageList)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?) .
  eq p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,fromKernel(mt),mem-in(mtLL),mem-out(mtLL),toKernel(mt)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,M?:Message?)
    = p(NWC:NetWebProcConfig,WIS:WebProcInfoSet,NIS:NetProcInfoSet,M?:Message?) .
  eq p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,fromKernel(ML:MessageList),loading(false)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?)
    = p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,fromKernel(mt),loading(false)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?) .
  eq p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,fromKernel(NRM:NonRetMsg),loading(true)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?)
    = p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,fromKernel(mt),loading(true)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?) .
  eq p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,fromKernel(mt),toKernel(mt)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,M?:Message?)
    = p(NWC:NetWebProcConfig,WIS:WebProcInfoSet,NIS:NetProcInfoSet,M?:Message?) .
  eq p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,fromKernel(ML:MessageList @ NRM:NonRetMsg),loading(true)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?)
    = p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,fromKernel(ML:MessageList),loading(true)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?) .
  eq p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,fromKernel(NRM:NonRetMsg @ ML2:MessageList),loading(true)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?)
    = p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,fromKernel(ML2:MessageList),loading(true)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?) .
  eq p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,fromKernel(ML:MessageList @ NRM:NonRetMsg @ ML2:MessageList),loading(true)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?)
    = p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,fromKernel(ML:MessageList @ ML2:MessageList),loading(true)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?) .
  eq p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,loading(false),toKernel(NFL:NonFetchMsgList)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?)
    = p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,loading(false),toKernel(mt)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?) .
  eq pid-in-netlabels?(NNPI:NonNetProcId,NIS:NetProcInfoSet)
    = false .
  eq pid-in-netlabels?(network,NIS:NetProcInfoSet)
    = false .
  eq pid-in-netlabels?(webapp,NIS:NetProcInfoSet)
    = false .
  eq pid-in-netlabels?(network(N:Nat),NIS:NetProcInfoSet)
    = nat-in-netlabels?(N:Nat,NIS:NetProcInfoSet) .
  eq pid-in-weblabels?(NWAI:NonWebProcId,WIS:WebProcInfoSet)
    = false .
  eq pid-in-weblabels?(network,WIS:WebProcInfoSet)
    = false .
  eq pid-in-weblabels?(webapp,WIS:WebProcInfoSet)
    = false .
  eq pid-in-weblabels?(webapp(N:Nat),WIS:WebProcInfoSet)
    = nat-in-weblabels?(N:Nat,WIS:WebProcInfoSet) .
  eq weblabels-dupl?(mtWPIS)
    = false .
  eq weblabels-dupl?(WIS:WebProcInfoSet,wp pi(WAI:WebProcId,L:Label),wp pi(WAI:WebProcId,L':Label))
    = true .
  eq weblabels-dupl?(pi(WAI:WebProcId,L:Label))
    = false .
  eq webproc-url-in-conf?(none)
    = false .
  eq webproc-url-in-conf?(C:Configuration < NWAI:NonWebProcId | A:AttributeSet >)
    = webproc-url-in-conf?(C:Configuration) .
  eq webproc-url-in-conf?(C:Configuration < WAI:WebProcId | A:AttributeSet,URL(L:Label)>)
    = true .
  eq webproc-url-netproc-in-conf?(C:Configuration < WAI:WebProcId | A:AttributeSet,URL(L:Label)> < NPI:NetProcId | A':AttributeSet >)
    = true .
  ceq attr-dupl?(AS:AttributeSet,A:Attribute)
    = attr-dupl?(AS:AttributeSet)
    if in-attrset?(A:Attribute | AS:AttributeSet)= false .
  ceq attr-subset?(AS:AttributeSet,A:Attribute | AS':AttributeSet)
    = false
    if in-attrset?(A:Attribute | AS':AttributeSet)= false .
  ceq attr-subset?(AS:AttributeSet,A:Attribute | AS':AttributeSet)
    = attr-subset?(AS:AttributeSet | AS':AttributeSet)
    if in-attrset?(A:Attribute | AS':AttributeSet)= true .
  ceq conf-attr-dupl?(C:Configuration < PI:ProcessId | A:AttributeSet >)
    = true
    if attr-dupl?(A:AttributeSet)= true .
  ceq conf-attr-dupl?(C:Configuration < PI:ProcessId | A:AttributeSet,At:Attribute,At':Attribute >)
    = conf-attr-dupl?(C:Configuration < PI:ProcessId | A:AttributeSet >)
    if At:Attribute ~a At':Attribute = false .
  ceq conf-dupl?(C:Configuration < PI:ProcessId | none >)
    = conf-dupl?(C:Configuration)
    if in-conf?(PI:ProcessId,C:Configuration)= false .
  ceq fresh-np-id?(network(1 + N:Nat),C:Configuration)
    = true
    if fresh-np-id?(network(N:Nat),C:Configuration)= true .
  ceq fresh-wp-id?(webapp(1 + N:Nat),C:Configuration)
    = true
    if fresh-wp-id?(webapp(N:Nat),C:Configuration)= true .
  ceq in-attrset?(A:Attribute | AS:AttributeSet,A':Attribute)
    = in-attrset?(A:Attribute | AS:AttributeSet)
    if A:Attribute ~a A':Attribute = false .
  ceq in-conf?(PI:ProcessId,C:Configuration < PI':ProcessId | A':AttributeSet >)
    = in-conf?(PI:ProcessId,C:Configuration)
    if PI:ProcessId ~p PI':ProcessId = false .
  ceq inlbl-by-pid(NPI:NetProcId,NIS:NetProcInfoSet,np pi(NPI':NetProcId,IN:Label,OUT:Label))
    = inlbl-by-pid(NPI:NetProcId,NIS:NetProcInfoSet)
    if NPI:NetProcId ~p NPI':NetProcId = false .
  ceq inlbl-in-netlabels?(L:Label,NIS:NetProcInfoSet,np pi(NPI:NetProcId,IN:Label,OUT:Label))
    = inlbl-in-netlabels?(L:Label,NIS:NetProcInfoSet)
    if L:Label ~l IN:Label = false .
  ceq lbl-in-weblabels?(L:Label,WIS:WebProcInfoSet,wp pi(WAI:WebProcId,L':Label))
    = lbl-in-weblabels?(L:Label,WIS:WebProcInfoSet)
    if L:Label ~l L':Label = false .
  ceq matching-procs1?(NI:NetProcId,L:Label,NPIS:NetProcInfoSet,np pi(NI':NetProcId,L':Label,L'':Label))
    = matching-procs1?(NI:NetProcId,L:Label,NPIS:NetProcInfoSet)
    if NI:NetProcId ~p NI':NetProcId and L:Label ~l L':Label = false .
  ceq matching-procs?(NI:NetProcId,WI:WebProcId,WPIS:WebProcInfoSet,wp pi(WI':WebProcId,L:Label),NPIS:NetProcInfoSet)
    = matching-procs?(NI:NetProcId,WI:WebProcId,WPIS:WebProcInfoSet,NPIS:NetProcInfoSet)
    if WI:WebProcId ~p WI':WebProcId = false .
  ceq metadata-match?(C:Configuration,NWIS:NeWebProcInfoSet,NNIS:NeNetProcInfoSet)
    = false
    if webproc-url-netproc-in-conf?(C:Configuration)= false .
  ceq metadata-match?(C:Configuration,NWIS:NeWebProcInfoSet,mtNPIS)
    = false
    if webproc-url-in-conf?(C:Configuration)= false .
  ceq metadata-match?(C:Configuration,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NPI:NetProcId,L:Label,L':Label))
    = false
    if lbl-in-weblabels?(L:Label,WIS:WebProcInfoSet)= false .
  ceq metadata-match?(C:Configuration,WIS:WebProcInfoSet,wp pi(WAI:WebProcId,L:Label),NIS:NetProcInfoSet)
    = false
    if inlbl-in-netlabels?(L:Label,NIS:NetProcInfoSet)= false .
  ceq nat-in-netlabels?(N:Nat,NIS:NetProcInfoSet,np pi(network(M:Nat),IN:Label,OUT:Label))
    = nat-in-netlabels?(N:Nat,NIS:NetProcInfoSet)
    if N:Nat ~n M:Nat = false .
  ceq nat-in-weblabels?(N:Nat,WIS:WebProcInfoSet,wp pi(webapp(M:Nat),L:Label))
    = nat-in-weblabels?(N:Nat,WIS:WebProcInfoSet)
    if N:Nat ~n M:Nat = false .
  ceq netlabels-dupl?(NIS:NetProcInfoSet,np pi(NPI:NetProcId,L:Label,L':Label))
    = netlabels-dupl?(NIS:NetProcInfoSet)
    if pid-in-netlabels?(NPI:NetProcId,NIS:NetProcInfoSet)= false .
  ceq np-by-lbl?(L':Label,NPIS:NetProcInfoSet,np pi(network(N:Nat),L:Label,L'':Label))
    = np-by-lbl?(L':Label,NPIS:NetProcInfoSet)
    if L':Label ~l L'':Label = false .
  ceq nwp-reqattrs?(C:Configuration < NPI:NetProcId | A:AttributeSet >)
    = false
    if attr-subset?(toKernel(mt),fromKernel(mt),returnTo(ui),mem-in(nolabel),mem-out(nolabel)| A:AttributeSet)= false .
  ceq nwp-reqattrs?(C:Configuration < WAI:WebProcId | A:AttributeSet >)
    = false
    if attr-subset?(toKernel(mt),fromKernel(mt),URL(about-blank),rendered(about-blank),loading(true)| A:AttributeSet)= false .
  ceq outlbl-by-pid(NPI:NetProcId,NIS:NetProcInfoSet,np pi(NPI':NetProcId,IN:Label,OUT:Label))
    = outlbl-by-pid(NPI:NetProcId,NIS:NetProcInfoSet)
    if NPI:NetProcId ~p NPI':NetProcId = false .
  ceq p(NWC:NetWebProcConfig,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?)
    = p(NWC:NetWebProcConfig,WIS:WebProcInfoSet,NIS:NetProcInfoSet,M?:Message?)
    if in-conf?(WI:WebProcId,NWC:NetWebProcConfig)= false /\ inlbl-in-netlabels?(IN:Label,NIS:NetProcInfoSet)= false .
  ceq p(NWC:NetWebProcConfig,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT:Label),M?:Message?)
    = p(NWC:NetWebProcConfig,WIS:WebProcInfoSet,NIS:NetProcInfoSet,M?:Message?)
    if in-conf?(WI:WebProcId,NWC:NetWebProcConfig)= false /\ in-conf?(NI:NetProcId,NWC:NetWebProcConfig)= false .
  ceq p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,fromKernel(ML:MessageList @ msg(PI:AbsPipeId,PI':AbsPipeId,MSG-FETCH-URL,OUT1:Label))>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,fromKernel(ML:MessageList)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    if PI:AbsPipeId ~p WI:WebProcId = true /\ PI':AbsPipeId ~p NI:NetProcId = true /\ OUT1:Label ~l OUT2:Label = true .
  ceq p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,fromKernel(msg(PI:AbsPipeId,PI':AbsPipeId,MSG-FETCH-URL,OUT1:Label)@ ML2:MessageList)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,fromKernel(ML2:MessageList)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    if PI:AbsPipeId ~p WI:WebProcId = true /\ PI':AbsPipeId ~p NI:NetProcId = true /\ OUT1:Label ~l OUT2:Label = true .
  ceq p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,fromKernel(ML:MessageList @ msg(PI:AbsPipeId,PI':AbsPipeId,MSG-FETCH-URL,OUT1:Label)@ ML2:MessageList)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,fromKernel(ML:MessageList @ ML2:MessageList)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    if PI:AbsPipeId ~p WI:WebProcId = true /\ PI':AbsPipeId ~p NI:NetProcId = true /\ OUT1:Label ~l OUT2:Label = true .
  ceq p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,fromKernel(msg(PI:AbsPipeId,PI':AbsPipeId,MSG-FETCH-URL,OUT1:Label))>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,fromKernel(mt)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    if PI:AbsPipeId ~p WI:WebProcId = true /\ PI':AbsPipeId ~p NI:NetProcId = true /\ OUT1:Label ~l OUT2:Label = true .
  ceq p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,mem-in(OUT1:Label)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,mem-in(nolabel)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    if OUT1:Label ~l OUT2:Label = true .
  ceq p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,mem-out(OUT1:Label)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,mem-out(nolabel)>,WIS:WebProcInfoSet,NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    if OUT1:Label ~l OUT2:Label = true .
  ceq p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,toKernel(ML:MessageList @ msg(PI:AbsPipeId,PI':AbsPipeId,MSG-RETURN-URL,OUT1:Label))>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,toKernel(ML:MessageList)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    if PI:AbsPipeId ~p NI:NetProcId = true /\ PI':AbsPipeId ~p WI:WebProcId = true /\ OUT1:Label ~l OUT2:Label = true .
  ceq p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,toKernel(msg(PI:AbsPipeId,PI':AbsPipeId,MSG-RETURN-URL,OUT1:Label)@ ML2:MessageList)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,toKernel(ML2:MessageList)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    if PI:AbsPipeId ~p NI:NetProcId = true /\ PI':AbsPipeId ~p WI:WebProcId = true /\ OUT1:Label ~l OUT2:Label = true .
  ceq p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,toKernel(ML:MessageList @ msg(PI:AbsPipeId,PI':AbsPipeId,MSG-RETURN-URL,OUT1:Label)@ ML2:MessageList)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,toKernel(ML:MessageList @ ML2:MessageList)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    if PI:AbsPipeId ~p NI:NetProcId = true /\ PI':AbsPipeId ~p WI:WebProcId = true /\ OUT1:Label ~l OUT2:Label = true .
  ceq p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,toKernel(msg(PI:AbsPipeId,PI':AbsPipeId,MSG-RETURN-URL,OUT1:Label))>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < NI:NetProcId | A:AttributeSet,toKernel(mt)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    if PI:AbsPipeId ~p NI:NetProcId = true /\ PI':AbsPipeId ~p WI:WebProcId = true /\ OUT1:Label ~l OUT2:Label = true .
  ceq p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,fromKernel(ML:MessageList @ msg(PI:AbsPipeId,PI':AbsPipeId,MSG-RETURN-URL,OUT1:Label)),loading(true)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,fromKernel(ML:MessageList),loading(true)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    if PI:AbsPipeId ~p NI:NetProcId = true /\ PI':AbsPipeId ~p WI:WebProcId = true /\ OUT1:Label ~l OUT2:Label = true .
  ceq p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,fromKernel(msg(PI:AbsPipeId,PI':AbsPipeId,MSG-RETURN-URL,OUT1:Label)@ ML2:MessageList),loading(true)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,fromKernel(ML2:MessageList),loading(true)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    if PI:AbsPipeId ~p NI:NetProcId = true /\ PI':AbsPipeId ~p WI:WebProcId = true /\ OUT1:Label ~l OUT2:Label = true .
  ceq p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,fromKernel(ML:MessageList @ msg(PI:AbsPipeId,PI':AbsPipeId,MSG-RETURN-URL,OUT1:Label)@ ML2:MessageList),loading(true)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,fromKernel(ML:MessageList @ ML2:MessageList),loading(true)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    if PI:AbsPipeId ~p NI:NetProcId = true /\ PI':AbsPipeId ~p WI:WebProcId = true /\ OUT1:Label ~l OUT2:Label = true .
  ceq p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,fromKernel(msg(PI:AbsPipeId,PI':AbsPipeId,MSG-RETURN-URL,OUT1:Label)),loading(true)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    = p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,fromKernel(mt),loading(true)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,np pi(NI:NetProcId,IN:Label,OUT2:Label),M?:Message?)
    if PI:AbsPipeId ~p NI:NetProcId = true /\ PI':AbsPipeId ~p WI:WebProcId = true /\ OUT1:Label ~l OUT2:Label = true .
  ceq p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,URL(OUT1:Label),loading(true),toKernel(NFL:NonFetchMsgList @ msg(PI:AbsPipeId,PI':AbsPipeId,MSG-FETCH-URL,OUT2:Label))>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?)
    = p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,URL(OUT1:Label),loading(false),toKernel(mt)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?)
    if PI:AbsPipeId ~p WI:WebProcId = true /\ network ~p PI':AbsPipeId = true /\ OUT1:Label ~l OUT2:Label = true .
  ceq p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,URL(OUT1:Label),loading(true),toKernel(msg(PI:AbsPipeId,PI':AbsPipeId,MSG-FETCH-URL,OUT2:Label)@ NFL2:NonFetchMsgList)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?)
    = p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,URL(OUT1:Label),loading(false),toKernel(mt)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?)
    if PI:AbsPipeId ~p WI:WebProcId = true /\ network ~p PI':AbsPipeId = true /\ OUT1:Label ~l OUT2:Label = true .
  ceq p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,URL(OUT1:Label),loading(true),toKernel(NFL:NonFetchMsgList @ msg(PI:AbsPipeId,PI':AbsPipeId,MSG-FETCH-URL,OUT2:Label)@ NFL2:NonFetchMsgList)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?)
    = p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,URL(OUT1:Label),loading(false),toKernel(mt)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?)
    if PI:AbsPipeId ~p WI:WebProcId = true /\ network ~p PI':AbsPipeId = true /\ OUT1:Label ~l OUT2:Label = true .
  ceq p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,URL(OUT1:Label),loading(true),toKernel(msg(PI:AbsPipeId,PI':AbsPipeId,MSG-FETCH-URL,OUT2:Label))>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?)
    = p(NWC:NetWebProcConfig < WI:WebProcId | A:AttributeSet,URL(OUT1:Label),loading(false),toKernel(mt)>,WIS:WebProcInfoSet,wp pi(WI:WebProcId,IN:Label),NIS:NetProcInfoSet,M?:Message?)
    if PI:AbsPipeId ~p WI:WebProcId = true /\ network ~p PI':AbsPipeId = true /\ OUT1:Label ~l OUT2:Label = true .
  ceq weblabels-dupl?(WIS:WebProcInfoSet,wp pi(WAI:WebProcId,L:Label))
    = weblabels-dupl?(WIS:WebProcInfoSet)
    if pid-in-weblabels?(WAI:WebProcId,WIS:WebProcInfoSet)= false .
  ceq webproc-url-in-conf?(C:Configuration < WAI:WebProcId | A:AttributeSet >)
    = webproc-url-in-conf?(C:Configuration)
    if in-attrset?(URL(about-blank)| A:AttributeSet)= false .
  ceq webproc-url-netproc-in-conf?(C:Configuration)
    = false
    if netproc-in-conf?(C:Configuration)= false .
  ceq webproc-url-netproc-in-conf?(C:Configuration)
    = false
    if webproc-url-in-conf?(C:Configuration)= false .
  eq X2:[LabelList,LabelSet,MaybeLabel]; mtLL
    = X2:[LabelList,LabelSet,MaybeLabel] [metadata "id" variant] .
  eq mtLL ; X2:[LabelList,LabelSet,MaybeLabel]
    = X2:[LabelList,LabelSet,MaybeLabel] [metadata "id" variant] .
  eq (X2:[LabelList,LabelSet,MaybeLabel]; mtLL); Y2:[LabelList,LabelSet,MaybeLabel]
    = X2:[LabelList,LabelSet,MaybeLabel]; Y2:[LabelList,LabelSet,MaybeLabel] [metadata "id" variant] .
  eq N:Nat <= N:Nat + M:Nat
    = true [variant] .
  eq (N:Nat + P:NzNat)<= N:Nat
    = false [variant] .
  eq N:Nat < N:Nat + P:NzNat
    = true [variant] .
  eq (N:Nat + M:Nat)< N:Nat
    = false [variant] .
  eq X3:[Message?,MessageList]@ mt
    = X3:[Message?,MessageList] [metadata "id" variant] .
  eq mt @ X3:[Message?,MessageList]
    = X3:[Message?,MessageList] [metadata "id" variant] .
  eq (X3:[Message?,MessageList]@ mt)@ Y3:[Message?,MessageList]
    = X3:[Message?,MessageList]@ Y3:[Message?,MessageList] [metadata "id" variant] .
  eq false and B:Bool
    = false [variant] .
  eq true and B:Bool
    = B:Bool [variant] .
  eq false or B:Bool
    = B:Bool [variant] .
  eq true or B:Bool
    = true [variant] .
  eq L:Label ~l L:Label
    = true [variant] .
  eq about-blank ~l url(N:Nat)
    = false [variant] .
  eq url(N:Nat)~l url(N':Nat)
    = N:Nat ~n N':Nat [variant] .
  eq N:Nat ~n N:Nat
    = true [variant] .
  eq N:Nat ~n N:Nat + P:NzNat
    = false [variant] .
  eq DiId:DisplayId ~p KeId:KernelId
    = false [variant] .
  eq DiId:DisplayId ~p NPId:NetProcId
    = false [variant] .
  eq DiId:DisplayId ~p UiId:UIId
    = false [variant] .
  eq DiId:DisplayId ~p WPMId:WebProcMgrId
    = false [variant] .
  eq KeId:KernelId ~p NPId:NetProcId
    = false [variant] .
  eq KeId:KernelId ~p UiId:UIId
    = false [variant] .
  eq NPId:NetProcId ~p UiId:UIId
    = false [variant] .
  eq PId:ProcessId ~p PId:ProcessId
    = true [variant] .
  eq WPId:WebProcId ~p DiId:DisplayId
    = false [variant] .
  eq WPId:WebProcId ~p KeId:KernelId
    = false [variant] .
  eq WPId:WebProcId ~p NPId:NetProcId
    = false [variant] .
  eq WPId:WebProcId ~p UiId:UIId
    = false [variant] .
  eq WPId:WebProcId ~p WPMId:WebProcMgrId
    = false [variant] .
  eq WPMId:WebProcMgrId ~p KeId:KernelId
    = false [variant] .
  eq WPMId:WebProcMgrId ~p NPId:NetProcId
    = false [variant] .
  eq WPMId:WebProcMgrId ~p UiId:UIId
    = false [variant] .
  eq network ~p network(N:Nat)
    = false [variant] .
  eq webapp ~p webapp(N:Nat)
    = false [variant] .
  eq network(N:Nat)~p network(N':Nat)
    = N:Nat ~n N':Nat [variant] .
  eq webapp(N:Nat)~p webapp(N':Nat)
    = N:Nat ~n N':Nat [variant] .
  eq nat-in-netlabels?(N:Nat,NIS:NetProcInfoSet,np pi(network(N:Nat),IN:Label,OUT:Label))
    = true [variant] .
  eq nat-in-weblabels?(N:Nat,WIS:WebProcInfoSet,wp pi(webapp(N:Nat),L:Label))
    = true [variant] .
  eq not false
    = true [variant] .
  eq not true
    = false [variant] .
  eq np-by-lbl?(L':Label,NPIS:NetProcInfoSet,np pi(network(N:Nat),L:Label,L':Label))
    = true [variant] .
  rl {C:Configuration}
    => [C:Configuration] [label stop] .
  rl {Cnf:Configuration < NI:NetProcId | Att:AttributeSet,in(LL:LabelList),mem-in(L:Label)>}
    => {Cnf:Configuration < NI:NetProcId | Att:AttributeSet,in(LL:LabelList ; L:Label),mem-in(nolabel)>} [label proc-in] .
  rl {Cnf:Configuration < NI:NetProcId | Att:AttributeSet,mem-out(nolabel),out(L:Label)>}
    => {Cnf:Configuration < NI:NetProcId | Att:AttributeSet,mem-out(L:Label),out(mtLL)>} [label proc-out] .
  rl {Cnf:Configuration < NI:NetProcId | Att:AttributeSet,mem-out(nolabel),out(L:Label ; LL:LabelList)>}
    => {Cnf:Configuration < NI:NetProcId | Att:AttributeSet,mem-out(L:Label),out(LL:LabelList)>} [label proc-out] .
  rl {Cnf:Configuration < NI:NetProcId | Att:AttributeSet,fromKernel(msg(PPI2:PipeId,NI:NetProcId,MSG-FETCH-URL,L:Label)@ ML':MessageList),out(LL:LabelList),returnTo(PPI1:PipeId)>}
    => {Cnf:Configuration < NI:NetProcId | Att:AttributeSet,fromKernel(ML':MessageList),out(LL:LabelList ; L:Label),returnTo(PPI2:PipeId)>} [label request-from-webapp] .
  rl {Cnf:Configuration < NI:NetProcId | Att:AttributeSet,fromKernel(msg(PPI2:PipeId,NI:NetProcId,MSG-FETCH-URL,L:Label)),out(LL:LabelList),returnTo(PPI1:PipeId)>}
    => {Cnf:Configuration < NI:NetProcId | Att:AttributeSet,fromKernel(mt),out(LL:LabelList ; L:Label),returnTo(PPI2:PipeId)>} [label request-from-webapp] .
  rl {Cnf:Configuration < NI:NetProcId | Att:AttributeSet,in(L:Label),returnTo(PPI1:PipeId),toKernel(ML:MessageList)>}
    => {Cnf:Configuration < NI:NetProcId | Att:AttributeSet,in(mtLL),returnTo(PPI1:PipeId),toKernel(ML:MessageList @ msg(NI:NetProcId,PPI1:PipeId,MSG-RETURN-URL,L:Label))>} [label msg-to-kernel] .
  rl {Cnf:Configuration < NI:NetProcId | Att:AttributeSet,in(L:Label ; LL:LabelList),returnTo(PPI1:PipeId),toKernel(ML:MessageList)>}
    => {Cnf:Configuration < NI:NetProcId | Att:AttributeSet,in(LL:LabelList),returnTo(PPI1:PipeId),toKernel(ML:MessageList @ msg(NI:NetProcId,PPI1:PipeId,MSG-RETURN-URL,L:Label))>} [label msg-to-kernel] .
  rl {Cnf:Configuration < WI:WebProcId | Att:AttributeSet,URL(L':Label),fromKernel(msg(PPI1:PipeId,WI:WebProcId,MSG-RETURN-URL,L2:Label)@ ML:MessageList),loading(true),rendered(L:Label)>}
    => {Cnf:Configuration < WI:WebProcId | Att:AttributeSet,URL(L':Label),fromKernel(ML:MessageList),loading(true),rendered(L2:Label)>} [label render] .
  rl {Cnf:Configuration < WI:WebProcId | Att:AttributeSet,URL(L':Label),fromKernel(msg(PPI1:PipeId,WI:WebProcId,MSG-RETURN-URL,L2:Label)),loading(true),rendered(L:Label)>}
    => {Cnf:Configuration < WI:WebProcId | Att:AttributeSet,URL(L':Label),fromKernel(mt),loading(true),rendered(L2:Label)>} [label render] .
  rl {Cnf:Configuration < WI:WebProcId | Att:AttributeSet,URL(L':Label),loading(false),rendered(L:Label),toKernel(ML:MessageList)>}
    => {Cnf:Configuration < WI:WebProcId | Att:AttributeSet,URL(L':Label),loading(true),rendered(L:Label),toKernel(ML:MessageList @ msg(WI:WebProcId,network,MSG-FETCH-URL,L':Label))>} [label fetch] .
  rl {Cnf:Configuration < nic | Att:AttributeSet,in(LL:LabelList),nic-out(L:Label & LS:LabelSet)>}
    => {Cnf:Configuration < nic | Att:AttributeSet,in(LL:LabelList ; L:Label),nic-out(LS:LabelSet)>} [label nic1] .
  rl {Cnf:Configuration < display | Att2:AttributeSet,activeWebapp(WI:WebProcId),displayedContent(L3:Label)> < kernel | Att:AttributeSet,displayedTopBar(L2:Label),handledCurrently(msg(ui,WI':WebProcId,MSG-SWITCH-TAB,L1:Label)),weblabels(WPIS:WebProcInfoSet,wp pi(WI':WebProcId,L':Label))>}
    => {Cnf:Configuration < display | Att2:AttributeSet,activeWebapp(WI':WebProcId),displayedContent(about-blank)> < kernel | Att:AttributeSet,displayedTopBar(L':Label),handledCurrently(none),weblabels(WPIS:WebProcInfoSet,wp pi(WI':WebProcId,L':Label))>} [label tab-change] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(PPI1:PipeId,PPI2:PipeId,MT:MsgType,L:Label))> < PPI2:PipeId | Att2:AttributeSet,fromKernel(ML:MessageList)>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none)> < PPI2:PipeId | Att2:AttributeSet,fromKernel(ML:MessageList @ msg(PPI1:PipeId,PPI2:PipeId,MT:MsgType,L:Label))>} [label kernelForwardsOPMessage] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet)> < PPI1:PipeId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,PPI2:PipeId,MT:MsgType,L:Label)@ ML:MessageList)>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet)> < PPI1:PipeId | Att2:AttributeSet,toKernel(ML:MessageList)>} [label kernelReceivesOPMessage-pa10] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet)> < PPI1:PipeId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,PPI2:PipeId,MT:MsgType,L:Label))>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet)> < PPI1:PipeId | Att2:AttributeSet,toKernel(mt)>} [label kernelReceivesOPMessage-pa10] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(NNPI1:NonNetPipeId,webapp,MT:MsgType))> < NNPI1:NonNetPipeId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,WI:WebProcId,MT:MsgType,L:Label)@ ML:MessageList)>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(NNPI1:NonNetPipeId,WI:WebProcId,MT:MsgType,L:Label)),msgPolicy(MP:PolicySet,ps policy(NNPI1:NonNetPipeId,webapp,MT:MsgType))> < NNPI1:NonNetPipeId | Att2:AttributeSet,toKernel(ML:MessageList)>} [label kernelReceivesOPMessage-pa3] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(NNPI1:NonNetPipeId,webapp,MT:MsgType))> < NNPI1:NonNetPipeId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,WI:WebProcId,MT:MsgType,L:Label))>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(NNPI1:NonNetPipeId,WI:WebProcId,MT:MsgType,L:Label)),msgPolicy(MP:PolicySet,ps policy(NNPI1:NonNetPipeId,webapp,MT:MsgType))> < NNPI1:NonNetPipeId | Att2:AttributeSet,toKernel(mt)>} [label kernelReceivesOPMessage-pa3] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(NWPI1:NonWebPipeId,network,MT:MsgType))> < NWPI1:NonWebPipeId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,NI:NetProcId,MT:MsgType,L:Label)@ ML:MessageList)>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(NWPI1:NonWebPipeId,NI:NetProcId,MT:MsgType,L:Label)),msgPolicy(MP:PolicySet,ps policy(NWPI1:NonWebPipeId,network,MT:MsgType))> < NWPI1:NonWebPipeId | Att2:AttributeSet,toKernel(ML:MessageList)>} [label kernelReceivesOPMessage-pa5] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(NWPI1:NonWebPipeId,network,MT:MsgType))> < NWPI1:NonWebPipeId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,NI:NetProcId,MT:MsgType,L:Label))>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(NWPI1:NonWebPipeId,NI:NetProcId,MT:MsgType,L:Label)),msgPolicy(MP:PolicySet,ps policy(NWPI1:NonWebPipeId,network,MT:MsgType))> < NWPI1:NonWebPipeId | Att2:AttributeSet,toKernel(mt)>} [label kernelReceivesOPMessage-pa5] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(PPI1:PipeId,PPI2:PipeId,MT:MsgType))> < PPI1:PipeId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,PPI2:PipeId,MT:MsgType,L:Label)@ ML:MessageList)>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(PPI1:PipeId,PPI2:PipeId,MT:MsgType,L:Label)),msgPolicy(MP:PolicySet,ps policy(PPI1:PipeId,PPI2:PipeId,MT:MsgType))> < PPI1:PipeId | Att2:AttributeSet,toKernel(ML:MessageList)>} [label kernelReceivesOPMessage-pa1] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(PPI1:PipeId,PPI2:PipeId,MT:MsgType))> < PPI1:PipeId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,PPI2:PipeId,MT:MsgType,L:Label))>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(PPI1:PipeId,PPI2:PipeId,MT:MsgType,L:Label)),msgPolicy(MP:PolicySet,ps policy(PPI1:PipeId,PPI2:PipeId,MT:MsgType))> < PPI1:PipeId | Att2:AttributeSet,toKernel(mt)>} [label kernelReceivesOPMessage-pa1] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(network,NWPI2:NonWebPipeId,MT:MsgType))> < NI:NetProcId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,NWPI2:NonWebPipeId,MT:MsgType,L:Label)@ ML:MessageList)>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(NI:NetProcId,NWPI2:NonWebPipeId,MT:MsgType,L:Label)),msgPolicy(MP:PolicySet,ps policy(network,NWPI2:NonWebPipeId,MT:MsgType))> < NI:NetProcId | Att2:AttributeSet,toKernel(ML:MessageList)>} [label kernelReceivesOPMessage-pa4] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(network,NWPI2:NonWebPipeId,MT:MsgType))> < NI:NetProcId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,NWPI2:NonWebPipeId,MT:MsgType,L:Label))>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(NI:NetProcId,NWPI2:NonWebPipeId,MT:MsgType,L:Label)),msgPolicy(MP:PolicySet,ps policy(network,NWPI2:NonWebPipeId,MT:MsgType))> < NI:NetProcId | Att2:AttributeSet,toKernel(mt)>} [label kernelReceivesOPMessage-pa4] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(ui,webapp,MSG-NEW-URL))> < ui | Att2:AttributeSet,toKernel(msg(ORG:PipeId,webapp,MSG-NEW-URL,L:Label)@ ML:MessageList)>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(ui,webapp,MSG-NEW-URL,L:Label)),msgPolicy(MP:PolicySet,ps policy(ui,webapp,MSG-NEW-URL))> < ui | Att2:AttributeSet,toKernel(ML:MessageList)>} [label kernelReceivesOPMessage-pa9] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(ui,webapp,MSG-NEW-URL))> < ui | Att2:AttributeSet,toKernel(msg(ORG:PipeId,webapp,MSG-NEW-URL,L:Label))>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(ui,webapp,MSG-NEW-URL,L:Label)),msgPolicy(MP:PolicySet,ps policy(ui,webapp,MSG-NEW-URL))> < ui | Att2:AttributeSet,toKernel(mt)>} [label kernelReceivesOPMessage-pa9] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(ui,webapp,MSG-SWITCH-TAB))> < ui | Att2:AttributeSet,toKernel(msg(ORG:PipeId,WI:WebProcId,MSG-SWITCH-TAB,L:Label)@ ML:MessageList)>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(ui,WI:WebProcId,MSG-SWITCH-TAB,L:Label)),msgPolicy(MP:PolicySet,ps policy(ui,webapp,MSG-SWITCH-TAB))> < ui | Att2:AttributeSet,toKernel(ML:MessageList)>} [label kernelReceivesOPMessage-pa8] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(ui,webapp,MSG-SWITCH-TAB))> < ui | Att2:AttributeSet,toKernel(msg(ORG:PipeId,WI:WebProcId,MSG-SWITCH-TAB,L:Label))>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(ui,WI:WebProcId,MSG-SWITCH-TAB,L:Label)),msgPolicy(MP:PolicySet,ps policy(ui,webapp,MSG-SWITCH-TAB))> < ui | Att2:AttributeSet,toKernel(mt)>} [label kernelReceivesOPMessage-pa8] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(webapp,NNPI2:NonNetPipeId,MT:MsgType))> < WI:WebProcId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,NNPI2:NonNetPipeId,MT:MsgType,L:Label)@ ML:MessageList)>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(WI:WebProcId,NNPI2:NonNetPipeId,MT:MsgType,L:Label)),msgPolicy(MP:PolicySet,ps policy(webapp,NNPI2:NonNetPipeId,MT:MsgType))> < WI:WebProcId | Att2:AttributeSet,toKernel(ML:MessageList)>} [label kernelReceivesOPMessage-pa2] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(webapp,NNPI2:NonNetPipeId,MT:MsgType))> < WI:WebProcId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,NNPI2:NonNetPipeId,MT:MsgType,L:Label))>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(WI:WebProcId,NNPI2:NonNetPipeId,MT:MsgType,L:Label)),msgPolicy(MP:PolicySet,ps policy(webapp,NNPI2:NonNetPipeId,MT:MsgType))> < WI:WebProcId | Att2:AttributeSet,toKernel(mt)>} [label kernelReceivesOPMessage-pa2] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(network,webapp,MT:MsgType)),netlabels(NPIS:NetProcInfoSet,np pi(NI:NetProcId,L:Label,L':Label)),weblabels(WPIS:WebProcInfoSet,wp pi(WI:WebProcId,L:Label))> < NI:NetProcId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,WI:WebProcId,MT:MsgType,L'':Label)@ ML:MessageList)>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(NI:NetProcId,WI:WebProcId,MT:MsgType,L'':Label)),msgPolicy(MP:PolicySet,ps policy(network,webapp,MT:MsgType)),netlabels(NPIS:NetProcInfoSet,np pi(NI:NetProcId,L:Label,L':Label)),weblabels(WPIS:WebProcInfoSet,wp pi(WI:WebProcId,L:Label))> < NI:NetProcId | Att2:AttributeSet,toKernel(ML:MessageList)>} [label kernelReceivesOPMessage-pa7-cc1a] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(network,webapp,MT:MsgType)),netlabels(NPIS:NetProcInfoSet,np pi(NI:NetProcId,L:Label,L':Label)),weblabels(WPIS:WebProcInfoSet,wp pi(WI:WebProcId,L:Label))> < NI:NetProcId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,WI:WebProcId,MT:MsgType,L'':Label))>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(NI:NetProcId,WI:WebProcId,MT:MsgType,L'':Label)),msgPolicy(MP:PolicySet,ps policy(network,webapp,MT:MsgType)),netlabels(NPIS:NetProcInfoSet,np pi(NI:NetProcId,L:Label,L':Label)),weblabels(WPIS:WebProcInfoSet,wp pi(WI:WebProcId,L:Label))> < NI:NetProcId | Att2:AttributeSet,toKernel(mt)>} [label kernelReceivesOPMessage-pa7-cc1a] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(webapp,network,MT:MsgType)),netlabels(NPIS:NetProcInfoSet,np pi(NI':NetProcId,L:Label,L':Label)),weblabels(WPIS:WebProcInfoSet,wp pi(WI:WebProcId,L:Label))> < WI:WebProcId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,NI:NetProcId,MT:MsgType,L':Label)@ ML:MessageList)>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(WI:WebProcId,NI':NetProcId,MT:MsgType,L':Label)),msgPolicy(MP:PolicySet,ps policy(webapp,network,MT:MsgType)),netlabels(NPIS:NetProcInfoSet,np pi(NI':NetProcId,L:Label,L':Label)),weblabels(WPIS:WebProcInfoSet,wp pi(WI:WebProcId,L:Label))> < WI:WebProcId | Att2:AttributeSet,toKernel(ML:MessageList)>} [label kernelReceivesOPMessage-pa6-cc2a] .
  rl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(webapp,network,MT:MsgType)),netlabels(NPIS:NetProcInfoSet,np pi(NI':NetProcId,L:Label,L':Label)),weblabels(WPIS:WebProcInfoSet,wp pi(WI:WebProcId,L:Label))> < WI:WebProcId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,NI:NetProcId,MT:MsgType,L':Label))>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(WI:WebProcId,NI':NetProcId,MT:MsgType,L':Label)),msgPolicy(MP:PolicySet,ps policy(webapp,network,MT:MsgType)),netlabels(NPIS:NetProcInfoSet,np pi(NI':NetProcId,L:Label,L':Label)),weblabels(WPIS:WebProcInfoSet,wp pi(WI:WebProcId,L:Label))> < WI:WebProcId | Att2:AttributeSet,toKernel(mt)>} [label kernelReceivesOPMessage-pa6-cc2a] .
  rl {Cnf:Configuration < display | Att2:AttributeSet,activeWebapp(WI:WebProcId),displayedContent(L':Label)> < kernel | Att:AttributeSet,displayedTopBar(L:Label),handledCurrently(msg(ui,webapp,MSG-NEW-URL,URL:Label)),weblabels(WPIS:WebProcInfoSet)> < webappmgr | Att3:AttributeSet,nextWPN(N:Nat)>}
    => {Cnf:Configuration < display | Att2:AttributeSet,activeWebapp(webapp(N:Nat)),displayedContent(about-blank)> < kernel | Att:AttributeSet,displayedTopBar(URL:Label),handledCurrently(none),weblabels(WPIS:WebProcInfoSet,wp pi(webapp(N:Nat),URL:Label))> < webappmgr | Att3:AttributeSet,nextWPN(1 + N:Nat)> < webapp(N:Nat)| URL(URL:Label),fromKernel(mt),loading(false),rendered(about-blank),toKernel(mt)>} [label new-url] .
  rl {Cnf:Configuration < kernel | Att2:AttributeSet,netlabels(NPIS:NetProcInfoSet,np pi(NI:NetProcId,L:Label,L':Label))> < nic | Att3:AttributeSet,in(L':Label)> < NI:NetProcId | Att:AttributeSet,mem-in(nolabel)>}
    => {Cnf:Configuration < kernel | Att2:AttributeSet,netlabels(NPIS:NetProcInfoSet,np pi(NI:NetProcId,L:Label,L':Label))> < nic | Att3:AttributeSet,in(mtLL)> < NI:NetProcId | Att:AttributeSet,mem-in(L':Label)>} [label mem-in] .
  rl {Cnf:Configuration < kernel | Att2:AttributeSet,netlabels(NPIS:NetProcInfoSet,np pi(NI:NetProcId,L:Label,L':Label))> < nic | Att3:AttributeSet,in(L':Label ; LL:LabelList)> < NI:NetProcId | Att:AttributeSet,mem-in(nolabel)>}
    => {Cnf:Configuration < kernel | Att2:AttributeSet,netlabels(NPIS:NetProcInfoSet,np pi(NI:NetProcId,L:Label,L':Label))> < nic | Att3:AttributeSet,in(LL:LabelList)> < NI:NetProcId | Att:AttributeSet,mem-in(L':Label)>} [label mem-in] .
  rl {Cnf:Configuration < kernel | Att2:AttributeSet,netlabels(NPIS:NetProcInfoSet,np pi(NI:NetProcId,L:Label,L':Label))> < nic | Att3:AttributeSet,nic-out(LS:LabelSet)> < NI:NetProcId | Att:AttributeSet,mem-out(L':Label)>}
    => {Cnf:Configuration < kernel | Att2:AttributeSet,netlabels(NPIS:NetProcInfoSet,np pi(NI:NetProcId,L:Label,L':Label))> < nic | Att3:AttributeSet,nic-out(L':Label & LS:LabelSet)> < NI:NetProcId | Att:AttributeSet,mem-out(nolabel)>} [label mem-out] .
  crl {Cnf:Configuration < display | Att2:AttributeSet,activeWebapp(WI:WebProcId),displayedContent(L:Label)> < WI:WebProcId | Att3:AttributeSet,rendered(L':Label)>}
    => {Cnf:Configuration < display | Att2:AttributeSet,activeWebapp(WI:WebProcId),displayedContent(L':Label)> < WI:WebProcId | Att3:AttributeSet,rendered(L':Label)>}
    if L:Label ~l L':Label = false [label change-display] .
  crl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(network,webapp,MT:MsgType)),netlabels(NPIS:NetProcInfoSet),weblabels(WPIS:WebProcInfoSet)> < NI:NetProcId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,WI:WebProcId,MT:MsgType,L'':Label)@ ML:MessageList)>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(network,webapp,MT:MsgType)),netlabels(NPIS:NetProcInfoSet),weblabels(WPIS:WebProcInfoSet)> < NI:NetProcId | Att2:AttributeSet,toKernel(ML:MessageList)>}
    if matching-procs?(NI:NetProcId,WI:WebProcId,WPIS:WebProcInfoSet,NPIS:NetProcInfoSet)= false [label kernelReceivesOPMessage-pa7-cc1b] .
  crl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(network,webapp,MT:MsgType)),netlabels(NPIS:NetProcInfoSet),weblabels(WPIS:WebProcInfoSet)> < NI:NetProcId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,WI:WebProcId,MT:MsgType,L'':Label))>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(network,webapp,MT:MsgType)),netlabels(NPIS:NetProcInfoSet),weblabels(WPIS:WebProcInfoSet)> < NI:NetProcId | Att2:AttributeSet,toKernel(mt)>}
    if matching-procs?(NI:NetProcId,WI:WebProcId,WPIS:WebProcInfoSet,NPIS:NetProcInfoSet)= false [label kernelReceivesOPMessage-pa7-cc1b] .
  crl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(webapp,network,MT:MsgType)),netlabels(NPIS:NetProcInfoSet),nextNPN(N:Nat),weblabels(WPIS:WebProcInfoSet,wp pi(WI:WebProcId,L:Label))> < WI:WebProcId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,NI:NetProcId,MT:MsgType,L':Label)@ ML:MessageList)>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(WI:WebProcId,network(N:Nat),MT:MsgType,L':Label)),msgPolicy(MP:PolicySet,ps policy(webapp,network,MT:MsgType)),netlabels(NPIS:NetProcInfoSet,np pi(network(N:Nat),L:Label,L':Label)),nextNPN(1 + N:Nat),weblabels(WPIS:WebProcInfoSet,wp pi(WI:WebProcId,L:Label))> < WI:WebProcId | Att2:AttributeSet,toKernel(ML:MessageList)> < network(N:Nat)| fromKernel(mt),in(mtLL),mem-in(nolabel),mem-out(nolabel),out(mtLL),returnTo(WI:WebProcId),toKernel(mt)>}
    if np-by-lbl?(L':Label,NPIS:NetProcInfoSet)= false [label kernelReceivesOPMessage-pa6-cc2b] .
  crl {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(none),msgPolicy(MP:PolicySet,ps policy(webapp,network,MT:MsgType)),netlabels(NPIS:NetProcInfoSet),nextNPN(N:Nat),weblabels(WPIS:WebProcInfoSet,wp pi(WI:WebProcId,L:Label))> < WI:WebProcId | Att2:AttributeSet,toKernel(msg(ORG:PipeId,NI:NetProcId,MT:MsgType,L':Label))>}
    => {Cnf:Configuration < kernel | Att:AttributeSet,handledCurrently(msg(WI:WebProcId,network(N:Nat),MT:MsgType,L':Label)),msgPolicy(MP:PolicySet,ps policy(webapp,network,MT:MsgType)),netlabels(NPIS:NetProcInfoSet,np pi(network(N:Nat),L:Label,L':Label)),nextNPN(1 + N:Nat),weblabels(WPIS:WebProcInfoSet,wp pi(WI:WebProcId,L:Label))> < WI:WebProcId | Att2:AttributeSet,toKernel(mt)> < network(N:Nat)| fromKernel(mt),in(mtLL),mem-in(nolabel),mem-out(nolabel),out(mtLL),returnTo(WI:WebProcId),toKernel(mt)>}
    if np-by-lbl?(L':Label,NPIS:NetProcInfoSet)= false [label kernelReceivesOPMessage-pa6-cc2b] .
endm
