load ibos-sop-base.maude
load ibos-sop-base-noid.maude

set show advisories off .
set print attribute on .
---set print with parentheses on .

load ../../rltool-lib.maude

fmod FOFORMSIMPLIFY-IMP-IMPL-EXT is
  pr FOFORMSIMPLIFY-IMP-IMPL .

  var D : Disj .
  var T T' : Term .
  var L L' : TermList .

  --- these hold inductively
  eq D \/ 'true.Bool != '_~_['false.Bool,'_bwa<=_[T,T']] \/ 'true.Bool ?= '_~_['false.Bool,'_bwa<=_['_+_['1.NzNat*,T],T']] = tt .
  eq D \/ 'true.Bool != '_~_['false.Bool,'_bnp<=_[T,T']] \/ 'true.Bool ?= '_~_['false.Bool,'_bnp<=_['_+_['1.NzNat*,T],T']] = tt .
endfm

select RLTOOL .
loop rltl-init .

(select IBOS-SOP .)

--- Solved:
--- 1. kernelReceivesOPMessage-pa7-cc1b
--- 2. kernelReceivesOPMessage-pa7-cc1a
--- 3. kernelReceivesOPMessage-pa6-cc2b
--- 4. kernelReceivesOPMessage-pa6-cc2a

---(select-rls new-url .)
---(select-rls stop .)
---(select-rls kernelForwardsOPMessage .)

(select-rls new-url stop .)

(use tool conrew for validity on IBOS-SOP-PRED-NOID with FOFORMSIMPLIFY-IMPL .)
(use tool varsat for validity on KERNEL-POLICIES-NONFVP .)
(declare-vars (C:NeConfiguration) U (WPIS:WebappProcInfoSet) U (NPIS:NetworkProcInfoSet) U (MSG:Message) U
              (PS:PolicySet) U (NNP:Nat) U (NWA:Nat) U (U:Label) U (B:Bool) U (B':Bool) .)
(def-term-set ([C]) | true .)
--- INV is a generalized multiset equality between:
--- [1] set of fromKernel messages at the beginning of a list in a netproc
--- [2] labels in WebappInfoSet and NetworkProcInfoSet
(inv sop4 to '`[_`] on
({ C
   < webappmgr | nextWAN(NWA) >
   < kernel | weblabels(WPIS), networklabels(NPIS), displayedTopBar(U), handledCurrently(MSG), msgPolicy(PS), nextNetworkProc(NNP) > } ) |
   (p4(C,WPIS,NPIS))                              = (true)   /\
   (p5(C,WPIS,NPIS))                              = (true)   /\
   (ch-p14(MSG,WPIS,NPIS,NNP))                    = (true)   /\
   --- these are strengthenings of the invariant above that allow the simplification rules to apply more often
   --- they are not strictly needed for correctness --- the invariant above should be enough
   (fresh-np-id(NNP,C))                           = (true)   /\
   (fresh-wa-id(NWA,C))                           = (true)   /\
   (dupl(C < webappmgr | nextWAN(NWA)         >
           < kernel    | nextNetworkProc(NNP) >)) = (false)
.)
(start-proof .)
--- set break on .
--- set print conceal on .
--- print conceal mod_is_sorts_._____endm fmod_is_sorts_.____endfm _;;_ ((_:_)) __ .
--- break select simp-action step-action .
(auto .)
--- (cases ({< kernel | handledCurrently(msg(N:NetProcId,W:WebAppId,MT:MsgType,OUT:Label)), AS:AttributeSet > C}) on MT:MsgType by (MSG-RETURN-URL) U (NR:NonRetMsg) .)
--- (cases+ ({C}) | ((true) = (B' a (B o (false ~ (MSG-RETURN-URL ~ MT:MsgType))))) on MT:MsgType by (MSG-RETURN-URL) U (NR:NonRetMsg) .)
