load ../../systems/ibos-sop-pred-nou.maude --- contextual rewriting
load ../../systems/ibos-sop-fvp-noau.maude --- varsat
load ../../systems/ibos-sop-noau.maude     --- everything

set show advisories off .
set print attribute on .
---set print with parentheses on .

load ../../rltool-lib.maude

--- NOTE: this property has expanded to encompass attributes:
---       display: activeWebapp, displayedContent
---       kernel: displayedTopBar, weblabels
---       webappmgr: nextWAN
--- NOTE: since we are not worried about ids of network processes here, the nextNetworkProc attribute probably doesn't matter
--- NOTE: due to the changeTab rule requiring synchronization between the weblabels attribute and the state of the system, we either need to:
---       [i]  use a recursive (non-FVP) predicate to describe the required relationship (strengthen the invariant + proof subcalculus to reason about it)
---       [ii] strengthen the changeTab rule in our specification by strengthening its condition


(select     IBOS-SOP-NOID .)
(use tool conrew  for validity         on IBOS-SOP-PRED-NOID with FOFORMSIMPLIFY-IMP-IMPL .)
(use tool conrew  for unsatisfiability on IBOS-SOP-PRED-NOID .)
(use tool varunif for varunif          on IBOS-SOP-FVP-NOID  .)

(select-rls! new-url change-display tab-change stop .)
(declare-vars (C:Configuration) U
              (NWP:Nat) U (NNP:Nat) U (DISP:Label) U (URL:Label) U (RNDR:Label) U (BAR:Label) U (W:ConcWebProcId) U
              (NIS:NetworkProcInfoSet) U (WIS:WebappProcInfoSet) U (PS:PolicySet) U (MSG:Message) U (B:Bool) U (FK:MessageList) U (TK:MessageList) .)
(def-term-set ([C]) | true .)
(inv to '`[_`] on ({C 
                    < display   | activeWebapp(W), displayedContent(DISP) > --- activeWebapp() process id refers to process in soup
                    < webappmgr | nextWAN(NWP) >
                    < kernel    | handledCurrently(MSG), msgPolicy(PS), networklabels(NIS),
                                  weblabels(WIS), displayedTopBar(URL), nextNetworkProc(NNP) > })

    | --- activeWebapp's id and URL appear in weblabels(), URL appears in displayedTopBar()

       (conf-dupl?(C < webappmgr | none > < kernel | none > < display | none >)) = (true) --- no duplicate process ids in soup
    /\ (conf-attr-dupl(C !c))               = (true)                                      --- no duplicate webapp attrs in any webapp
    /\ (fresh-wp-id?(W,C !c))               = (true)                                      --- NWP counter is larger than any current webapp id in Configuration
    /\ (fresh-weblabel?(W,WIS))             = (true)                                      --- NWP counter is larger than any current webapp id in weblabels()
    /\ (in-conf?(W,C))                      = (true)                                      --- the webapp id refers to a process
    /\ (weblabel-by-pid(W,WIS))             = (URL)                                       --- the webapp has a URL
    /\ (conf-labels-eqset?(NWC !c,WIS,NIS)) = (true)                                      --- ensure WIS and C are consistent
    /\ (weblabels-dupl?(WIS))               = (false)                                     --- no duplicate process ids in weblabels() set

    ---/\ ((W,URL) inWL C) = (tt)                                                         --- [W,URL] tuple exists in C
    ---/\ (DISP ~b1 RNDR) = (tt)                                                          --- DISP is about-blank or equal to RNDR
    ---/\ ((W,URL,RNDR) inWUR C) = (tt)                                                   --- activeWebapp/URL/RNDR all exist in the soup
    .)

set print attribute on .
print reveal _&_ .
(start-proof .)
(step .)
(list-goals .)
(auto .)
quit
