load ../../systems/ibos-preds-fvp-noau.maude --- varsat
load ../../systems/ibos-preds-nou.maude      --- contextual rewriting
load ../../systems/ibos-noau.maude           --- everything

set show advisories off .

load ../../rltool-lib.maude

fmod FOFORMSIMPLIFY-IMP-IMPL-EXT is
  pr FOFORMSIMPLIFY-IMP-IMPL .

  var D : Disj .
  var T T' : Term .
  var L L' : TermList .

  eq 'false.Bool ?= '_and_[T,T'] = 'false.Bool ?= T \/ 'false.Bool ?= T' .
  eq 'false.Bool != '_and_[T,T'] = 'false.Bool != T \/ 'false.Bool != T' .
  eq 'false.Bool ?= 'true.Bool   = ff .
  eq 'false.Bool != 'true.Bool   = tt .

  --- Lemmas needed for kernelReceivesOPMessage-pa9/10
  var LBL MSGL PI PI' WIS : Term .
  eq 'true.Bool != 'newurl-nodupl?[LBL,MSGL]
  \/ 'true.Bool != 'ui-consistent?['_@_['msg[PI,'webapp.AbsWebProcId,'MSG-NEW-URL.NonRetFetchMsgType,LBL],MSGL],WIS]
   = 'true.Bool != 'ui-consistent?[MSGL,WIS] .
endfm

select RLTOOL .
loop rltl-init .

(select IBOS-STOP-WITH-PREDS-NOID .)
(use tool conrew  for validity         on IBOS-PREDS-NOID with FOFORMSIMPLIFY-IMP-IMPL-EXT .)
(use tool conrew  for unsatisfiability on IBOS-PREDS-NOID .)
(use tool varunif for varunif          on IBOS-PREDS-FVP-NOID .)

--- Do not unify with invariant state:
--- 14. kernelReceivesOPMessage-pa1
--- 15. kernelReceivesOPMessage-pa2
--- 16. kernelReceivesOPMessage-pa3
--- 17. kernelReceivesOPMessage-pa4
--- 18. kernelReceivesOPMessage-pa5

--- Solved:
--- 1. fetch
--- 2. kernelReceivesOPMessage-pa7
--- 3. kernelReceivesOPMessage-pa6-a
--- 4. kernelReceivesOPMessage-pa6-b
--- 5. new-url
--- 6. kernelForwardsOPMessage
--- 7. render
--- 8. request-from-webapp
--- 9. proc-in
--- 10. proc-out
--- 11. msg-to-kernel
--- 12. mem-out
--- 13. mem-in
--- 19. kernelReceivesOPMessage-pa8
--- 20. kernelReceivesOPMessage-pa9
--- 21. change-display
--- 22. tab-change
--- 23. kernelReceivesOPMessage-pa10

(select-rls kernelReceivesOPMessage-pa10 .)

(declare-vars (C:Configuration) U (NWC:NetWebProcConfig) U (WIS:WebProcInfoSet) U (NIS:NetProcInfoSet) U (MSG?:Message?) U
              (NNP:Nat) U (NWP:Nat) U (CURR:Label) U (B:Bool) U (B':Bool) U (UIML:MessageList) U
	      (DISP:Label) U (NICIN:LabelList) U (NICOUT:LabelSet) U (NI:ConcNetProcId) U (NI?:NetProcId) U
	      (F:MessageList) U (T:MessageList) U (D:Label) U (L:Bool) U (U:Label) U (U':Label) U (U2:Label) U (IN:Label) U (IN2:Label) U (OUT:Label) U (OUT2:Label) U
	      (A:AttributeSet) U (A':AttributeSet) U (A'':AttributeSet) U (MT:MsgType) U (LL:LabelList) U (RNDR:Label) U
	      (NWI:ConcNetWebProcId) U (WI:ConcWebProcId) U (WI':ConcWebProcId) U (PP1:ConcPipeId) U (GPPI:PipeId) .)

(def-term-set ([C:Configuration]) | true .)

(inv abc to '`[_`] on
({ NWC
   < ui | toKernel(UIML) >
   < display | activeWebapp(WI), displayedContent(DISP) >
   < nic | in(NICIN), nic-out(NICOUT) >
   < webappmgr | nextWPN(NWP) >
   < kernel | weblabels(WIS), netlabels(NIS), displayedTopBar(CURR), handledCurrently(MSG?), nextNPN(NNP),
       msgPolicy(policy(webapp, network,MSG-FETCH-URL ),ps
                 policy(ui,     webapp, MSG-NEW-URL   ),ps
		 policy(ui,     webapp, MSG-SWITCH-TAB),ps
		 policy(network,webapp, MSG-RETURN-URL)) > }) |
   (p(NWC,WIS,NIS,MSG?))                                          = (true)  /\
   (nwp-reqattrs?(NWC !c))                                        = (true)  /\
   (conf-attr-dupl?(NWC !c))                                      = (false) /\
   (conf-labels-eqset?(NWC,WIS,NIS))                              = (true)  /\
   (weblabels-dupl?(WIS))                                         = (false) /\
   (netlabels-dupl?(NIS))                                         = (false) /\
   (conf-dupl?(NWC))                                              = (false) /\
   (fresh-wp-id?(webapp(NWP), NWC))                               = (true)  /\
   (fresh-np-id?(network(NNP),NWC))                               = (true)  /\
   (fresh-weblabel?(webapp(NWP),WIS))                             = (true)  /\
   (fresh-netlabel?(network(NNP),NIS))                            = (true)  /\
   (ui-consistent?(UIML,WIS))                                     = (true)  /\
   ---
   (netlabels-match?(NIS))                                        = (true)  /\
   (webapp-url-eqset?(NWC,WIS))                                   = (true)  /\
   (weblabel-by-pid(WI,WIS) ~l CURR)                              = (true)  /\
   (display-topbar-consistent?(WI,DISP,CURR,NWC))                 = (true)  /\
   (render-consistent?(NWC))                                      = (true)
.)

(start-proof .)

(auto .)

--- new-url, change-display, nic1
--- (auto .)

--- tab-change
--- (split ({ < WI | A > < kernel | weblabels(pi(WI,U),wp pi(WI',U'),wp WIS), A' > C }) by (webapp-url-render(WI',C)) = ((U,RNDR)) and (webapp-url-render(WI',C)) = (nopair) .)
--- (split ({ < WI | URL(U), A > < display | activeWebapp(WI), A' > < kernel | displayedTopBar(U'), A'' > C }) by (U ~l U') = (true) and (U ~l U') = (false) .)
--- (auto .)

--- fetch
--- (split ({ < WI | loading(B), URL(U), A > < kernel | weblabels(WIS), A' > C }) by (weblabel-by-pid(WI,WIS)) = (U) and (weblabel-by-pid(WI,WIS)) = (nolabel) .)
--- (split ({ < WI | A > < WI' | A' > C }) by (WI ~p WI') = (true) and (WI ~p WI') = (false) .)
--- (auto .)

--- render --- single process
--- (focus 240 -- 247, 252 -- 259 .)
--- (split ({ < WI | loading(true), A > < kernel | weblabels(WIS), A' > C }) by (weblabel-by-pid(WI,WIS)) = (IN) and (weblabel-by-pid(WI,WIS)) = (nolabel) .)
--- (split ({ C }) | (p(< WI | fromKernel(msg(PP1,WI,MSG-RETURN-URL,U) @ F), A > NWC,WIS,NIS,MSG?)) = (true) by (netlabelpair-by-pid(PP1,NIS)) = ((IN,OUT)) and (netlabelpair-by-pid(PP1,NIS)) = (nopair) .)
--- (split ({ C }) | (p(< WI | fromKernel(msg(PP1,WI,MSG-RETURN-URL,U)    ), A > NWC,WIS,NIS,MSG?)) = (true) by (netlabelpair-by-pid(PP1,NIS)) = ((IN,OUT)) and (netlabelpair-by-pid(PP1,NIS)) = (nopair) .)
--- (split ({ < WI | loading(true), A > < kernel | weblabels(pi(WI,IN),wp WIS), netlabels(pi(NI,IN2,OUT),np NIS), A' > C }) by (IN ~l IN2) = (true) and (IN ~l IN2) = (false) .)
--- (split ({ < WI | loading(true), rendered(U), A > < kernel | netlabels(pi(NI,IN,OUT),np NIS), A' > C }) by (U ~l OUT) = (true) and (U ~l OUT) = (false) .)
--- (split ({ < kernel | netlabels(pi(NI,IN2,OUT),np NIS), A > C }) by (IN2 ~l OUT) = (true) and (IN2 ~l OUT) = (false) .)
--- (split ({ C }) | (render-consistent?(< WI | URL(U), rendered(U'), A > NWC)) = (true) by (U' blank-or-equal U) = (true) and (U' blank-or-equal U) = (false) .)
--- (auto .)

--- render --- multi process
--- (focus 248 -- 251, 260 -- 263 .)
--- (split ({ < WI | loading(true),         A > < kernel | weblabels(             WIS), A' > C }) by (weblabel-by-pid(WI,WIS)) = (IN) and (weblabel-by-pid(WI,WIS)) = (nolabel) .)
--- (split ({ < WI | loading(true), URL(U), A > < kernel | weblabels(pi(WI,IN),wp WIS), A' > C }) by (U ~l IN) = (true) and (U ~l IN) = (false) .)
--- (split ({ C }) | (p(< WI | fromKernel(msg(PP1,WI,MSG-RETURN-URL,U) @ F), A > NWC,WIS,NIS,MSG?)) = (true) by (netlabelpair-by-pid(PP1,NIS)) = ((IN,OUT)) and (netlabelpair-by-pid(PP1,NIS)) = (nopair) .)
--- (split ({ C }) | (p(< WI | fromKernel(msg(PP1,WI,MSG-RETURN-URL,U)    ), A > NWC,WIS,NIS,MSG?)) = (true) by (netlabelpair-by-pid(PP1,NIS)) = ((IN,OUT)) and (netlabelpair-by-pid(PP1,NIS)) = (nopair) .)
--- (split ({ < WI | loading(true), A > < kernel | weblabels(pi(WI,IN),wp WIS), netlabels(pi(NI,IN2,OUT),np NIS), A' > C }) by (IN ~l IN2) = (true) and (IN ~l IN2) = (false) .)
--- (split ({ < WI | loading(true), rendered(U), A > < kernel | netlabels(pi(NI,IN,OUT),np NIS), A' > C }) by (U ~l OUT) = (true) and (U ~l OUT) = (false) .)
--- (split ({ < kernel | netlabels(pi(NI,IN2,OUT),np NIS), A > C }) by (IN2 ~l OUT) = (true) and (IN2 ~l OUT) = (false) .)
--- (split ({ C }) | (render-consistent?(< WI | URL(U),  rendered(U'), A > < WI' | A' > NWC)) = (true) by (U' blank-or-equal U) = (true) and (U' blank-or-equal U) = (false) .)
--- (split ({ C }) | (render-consistent?(< WI | URL(U),  rendered(U'), A' >             NWC)) = (true) by (U' blank-or-equal U) = (true) and (U' blank-or-equal U) = (false) .)
--- (split ({ < WI | A > < WI' | A' > C }) by (WI ~p WI') = (true) and (WI ~p WI') = (false) .)
--- (auto .)

--- request-from-webapp
--- the previous webproc is loaded
--- (split ({ C }) | (p(< NI | returnTo(PP1), A > NWC,WIS,NIS,MSG?)) = (true) by (proc-loaded?(NI,PP1,NIS,WIS,C)) = (true) and (proc-loaded?(NI,PP1,NIS,WIS,C)) = (false) .)
--- --- the webproc is loaded
--- (split ({ < NI | returnTo(PP1), A > < kernel | netlabels(NIS), weblabels(WIS), A' > C }) by (proc-loaded?(NI,PP1,NIS,WIS,C)) = (true) and (proc-loaded?(NI,PP1,NIS,WIS,C)) = (false) .)
--- --- outgoing matches netproc out
--- (split ({ < NI | out(LL ; U), A > < kernel | netlabels(pi(NI,IN,OUT),np NIS), A' > C }) by (U ~l OUT) = (true) and (U ~l OUT) = (false) .)
--- --- netproc labels match
--- (split ({ < kernel | netlabels(pi(NI,IN2,OUT),np NIS), A > C }) by (IN2 ~l OUT) = (true) and (IN2 ~l OUT) = (false) .)
--- --- the webprocs are not equal
--- (split ({ < kernel | weblabels(pi(WI,IN),wp pi(WI',IN2),wp WIS), A > C }) by (WI ~p WI') = (true) and (WI ~p WI') = (false) .)
--- (auto .)

--- proc-in
--- (split ({ < NI |             A > < kernel | netlabels(NIS), weblabels(WIS),  A' > C }) by (proc-loaded?(NI,none,NIS,WIS,C)) = (true) and (proc-loaded?(NI,none,NIS,WIS,C)) = (false) .)
--- (split ({ < NI | in(LL ; U), A > < kernel | netlabels(pi(NI,IN,OUT),np NIS), A' > C }) by (U  ~l OUT) = (true) and (U  ~l OUT) = (false) .)
--- (split ({ < NI |             A > < kernel | netlabels(pi(NI,IN,OUT),np NIS), A' > C }) by (IN ~l OUT) = (true) and (IN ~l OUT) = (false) .)
--- (auto .)

--- proc-out
--- (split ({ < NI |             A > < kernel | netlabels(NIS), weblabels(WIS), A' > C }) by (proc-loaded?(NI,none,NIS,WIS,C)) = (true) and (proc-loaded?(NI,none,NIS,WIS,C)) = (false) .)
--- (split ({ < NI | mem-out(U), A > < kernel | netlabels(pi(NI,IN,OUT),np NIS), A' > C }) by (U ~l OUT) = (true) and (U ~l OUT) = (false) .)
--- (split ({ < NI |             A > < kernel | netlabels(pi(NI,IN,OUT),np NIS), A' > C }) by (IN ~l OUT) = (true) and (IN ~l OUT) = (false) .)
--- (auto .)

--- msg-to-kernel
--- netproc loaded
--- (split ({ < NI | returnTo(PP1), A > < kernel | netlabels(NIS), weblabels(WIS), A' > C }) by (proc-loaded?(NI,PP1,NIS,WIS,C)) = (true) and (proc-loaded?(NI,PP1,NIS,WIS,C)) = (false) .)
--- --- outgoing matches netproc out
--- (split ({ < NI | toKernel(T @ msg(NI,PP1,MSG-RETURN-URL,U)), A > < kernel | netlabels(pi(NI,IN,OUT),np NIS), A' > C }) by (U ~l OUT) = (true) and (U ~l OUT) = (false) .)
--- --- netproc labels match
--- (split ({ < kernel | netlabels(pi(NI,IN2,OUT),np NIS), A > C }) by (IN2 ~l OUT) = (true) and (IN2 ~l OUT) = (false) .)
--- --- netproc and webproc ids match
--- (split ({ < NI | returnTo(WI),  A > < kernel | weblabels(pi(WI,IN),wp WIS), netlabels(pi(NI,IN2,OUT),np NIS), A' > C }) by (IN ~l IN2) = (true) and (IN ~l IN2) = (false) .)
--- ---
--- (auto .)

--- mem-out/mem-in
--- (split ({ < NI | A > < kernel | netlabels(NIS), weblabels(WIS), A' > C }) by (proc-loaded?(NI,none,NIS,WIS,C)) = (true) and (proc-loaded?(NI,none,NIS,WIS,C)) = (false) .)
--- (split ({ < NI | A > < kernel | netlabels(pi(NI,IN,OUT),np NIS), A' > C }) by (IN ~l OUT) = (true) and (IN ~l OUT) = (false) .)
--- (split ({ < kernel | weblabels(pi(WI,IN),wp pi(WI',IN2),wp WIS), A > C }) by (WI ~p WI') = (true) and (WI ~p WI') = (false) .)
--- (auto .)

--- pa6-a
--- pa6-b
--- (split ({ < WI | toKernel(T),                  A > C }) by (in-attrset?(URL(about-blank) | A)) = (true) and (in-attrset?(URL(about-blank) | A)) = (false) .)
--- (split ({ < WI | toKernel(T),                  A > C }) by (in-attrset?(loading(true)    | A)) = (true) and (in-attrset?(loading(true)    | A)) = (false) .)
--- (split ({ < WI | toKernel(T), loading(B:Bool), A > C }) by (B:Bool) = (true) and (B:Bool) = (false) .)
--- ---
--- (cases+ ({ C }) | (true) = (p(< WI |           toKernel(msg(PP1,NI?,MSG-FETCH-URL,U) @ T:MessageList), A > NWC,WIS,NIS,none)) on T:MessageList by (N:NonFetchMsgList) U (H:HasFetchMsgList) .)
--- ---
--- (split ({ C }) | (true) = (p(< WI |           toKernel(msg(PP1,NI?,MSG-FETCH-URL,U) @ T), A > NWC,WIS,NIS,none)) by (PP1 ~p WI)      = (true) and (PP1 ~p WI)      = (false) .)
--- (split ({ C }) | (true) = (p(< WI |           toKernel(msg(PP1,NI?,MSG-FETCH-URL,U)    ), A > NWC,WIS,NIS,none)) by (PP1 ~p WI)      = (true) and (PP1 ~p WI)      = (false) .)
--- ---
--- (split ({ C }) | (true) = (p(< WI | URL(OUT), toKernel(msg(PP1,NI?,MSG-FETCH-URL,U) @ T), A > NWC,WIS,NIS,none)) by (U ~l OUT)       = (true) and (U ~l OUT)       = (false) .)
--- (split ({ C }) | (true) = (p(< WI | URL(OUT), toKernel(msg(PP1,NI?,MSG-FETCH-URL,U)    ), A > NWC,WIS,NIS,none)) by (U ~l OUT)       = (true) and (U ~l OUT)       = (false) .)
--- ---
--- (split ({ C }) | (true) = (p(< WI |           toKernel(msg(PP1,NI?,MSG-FETCH-URL,U) @ T), A > NWC,WIS,NIS,none)) by (NI? ~p network) = (true) and (NI? ~p network) = (false) .)
--- (split ({ C }) | (true) = (p(< WI |           toKernel(msg(PP1,NI?,MSG-FETCH-URL,U)    ), A > NWC,WIS,NIS,none)) by (NI? ~p network) = (true) and (NI? ~p network) = (false) .)
--- ---
--- --- --- NB: only needed in 6-b case, so ensure match fails for 6-a
--- (split ({ < NI | A > < kernel | netlabels(pi(NI,IN,OUT),np NIS), A' > C }) by (IN ~l OUT) = (true) and (IN ~l OUT) = (false) .)
--- ---
--- (auto .)

--- pa7
--- (split ({ C }) | (true) = (p(< NI | toKernel(msg(PP1,WI,MSG-RETURN-URL,U) @ T), A > NWC,WIS,NIS,none)) by (PP1 ~p NI) = (true) and (PP1 ~p NI) = (false) .)
--- (split ({ C }) | (true) = (p(< NI | toKernel(msg(PP1,WI,MSG-RETURN-URL,U)    ), A > NWC,WIS,NIS,none)) by (PP1 ~p NI) = (true) and (PP1 ~p NI) = (false) .)
--- (split ({ < kernel | handledCurrently(msg(NI,WI,MSG-RETURN-URL,U)), netlabels(pi(NI,IN,OUT),np NIS), A > C }) by (U ~l OUT) = (true) and (U ~l OUT) = (false) .)
--- (split ({ < kernel | handledCurrently(msg(NI,WI,MSG-RETURN-URL,U)), netlabels(pi(NI,IN,OUT),np NIS), A > C }) by (IN ~l OUT) = (true) and (IN ~l OUT) = (false) .)
--- (split ({ < kernel | netlabels(NIS), weblabels(WIS), handledCurrently(msg(NI,WI,MSG-RETURN-URL,U)), A > C }) by (proc-loaded?(NI,WI,NIS,WIS,C)) = (true) and (proc-loaded?(NI,WI,NIS,WIS,C)) = (false) .)
--- (auto .)

--- pa8
--- (split ({ < kernel | handledCurrently(msg(ui,WI,MSG-SWITCH-TAB,OUT)), weblabels(WIS), A > C }) by (weblabel-by-pid(WI,WIS)) = (IN) and (weblabel-by-pid(WI,WIS)) = (nolabel) .)
--- (auto .)

--- pa9
--- (split ({ < ui | toKernel(T), A > < kernel | handledCurrently(msg(ui,webapp,MSG-NEW-URL,OUT)), A' > C}) by (newurl-nodupl?(OUT,T)) = (true) and (newurl-nodupl?(OUT,T)) = (false) .)
--- (auto .)

--- --- pa10
--- (split ({ < NWI:ConcNetWebProcId | toKernel(T), A > C }) by (NWI:ConcNetWebProcId) = (WI) and (NWI:ConcNetWebProcId) = (NI) .)
--- ---
--- --- WebProc Case
--- --- Split on Message Type
--- (cases+ ({ C }) | (p(< WI | toKernel(msg(PP1,GPPI,MT:MsgType,U) @ T), A > NWC,WIS,NIS,MSG?)) = (true) on MT:MsgType by (MSG-FETCH-URL) U (N:NonFetchMsgType) .)
--- (cases+ ({ C }) | (p(< WI | toKernel(msg(PP1,GPPI,MT:MsgType,U)    ), A > NWC,WIS,NIS,MSG?)) = (true) on MT:MsgType by (MSG-FETCH-URL) U (N:NonFetchMsgType) .)
--- --- Ensure attributes exist
--- (split  ({ < WI | toKernel(T), A > C }) by (in-attrset?(URL(about-blank) | A)) = (true) and (in-attrset?(URL(about-blank) | A)) = (false) .)
--- (split  ({ < WI | toKernel(T), A > C }) by (in-attrset?(loading(true) | A)) = (true) and (in-attrset?(loading(true) | A)) = (false) .)
--- --- Split on Message Payload
--- (split  ({ C }) | (p(< WI | toKernel(msg(PP1,GPPI,MSG-FETCH-URL,U) @ T), A > NWC,WIS,NIS,MSG?)) = (true) by (PP1 ~p WI) = (true) and (PP1 ~p WI) = (false) .)
--- (split  ({ C }) | (p(< WI | toKernel(msg(PP1,GPPI,MSG-FETCH-URL,U)    ), A > NWC,WIS,NIS,MSG?)) = (true) by (PP1 ~p WI) = (true) and (PP1 ~p WI) = (false) .)
--- (split  ({ C }) | (p(< WI | toKernel(msg(PP1,GPPI,MSG-FETCH-URL,U) @ T), A > NWC,WIS,NIS,MSG?)) = (true) by (GPPI ~p network) = (true) and (GPPI ~p network) = (false) .)
--- (split  ({ C }) | (p(< WI | toKernel(msg(PP1,GPPI,MSG-FETCH-URL,U)    ), A > NWC,WIS,NIS,MSG?)) = (true) by (GPPI ~p network) = (true) and (GPPI ~p network) = (false) .)
--- (split  ({ C }) | (p(< WI | URL(OUT), toKernel(msg(PP1,GPPI,MSG-FETCH-URL,U) @ T), A > NWC,WIS,NIS,MSG?)) = (true) by (U ~l OUT) = (true) and (U ~l OUT) = (false) .)
--- (split  ({ C }) | (p(< WI | URL(OUT), toKernel(msg(PP1,GPPI,MSG-FETCH-URL,U)    ), A > NWC,WIS,NIS,MSG?)) = (true) by (U ~l OUT) = (true) and (U ~l OUT) = (false) .)
--- --- Setup Metadata/Process/Message Consistency
--- (split  ({ C }) | (p(< WI | toKernel(T), A > NWC,WIS,NIS,MSG?)) = (true) by (weblabel-by-pid(WI,WIS)) = (IN) and (weblabel-by-pid(WI,WIS)) = (nolabel) .)
--- --- Ensure loading? flag is set
--- (split ({ < WI | toKernel(T), loading(L), A > C }) by (L) = (true) and (L) = (false) .)
--- ---
--- --- NetProc Case
--- --- Split on Message Type
--- (split  ({ C }) | (p(< NI | toKernel(msg(PP1,GPPI,MT:MsgType,   U) @ T), A > NWC,WIS,NIS,MSG?)) = (true) by (MT:MsgType) = (MSG-RETURN-URL) and (MT:MsgType) = (N:NonRetMsgType) .)
--- (split  ({ C }) | (p(< NI | toKernel(msg(PP1,GPPI,MT:MsgType,   U)    ), A > NWC,WIS,NIS,MSG?)) = (true) by (MT:MsgType) = (MSG-RETURN-URL) and (MT:MsgType) = (N:NonRetMsgType) .)
--- --- Handle Non-Ret Msg
--- (split  ({ C }) | (p(< NI | toKernel(msg(PP1,GPPI,N:NonRetMsgType,U) @ T), A > NWC,WIS,NIS,MSG?)) = (true) by (netlabelpair-by-pid(NI,NIS)) = ((IN,OUT)) and (netlabelpair-by-pid(NI,NIS)) = (nopair) .)
--- (split  ({ C }) | (p(< NI | toKernel(msg(PP1,GPPI,N:NonRetMsgType,U)    ), A > NWC,WIS,NIS,MSG?)) = (true) by (netlabelpair-by-pid(NI,NIS)) = ((IN,OUT)) and (netlabelpair-by-pid(NI,NIS)) = (nopair) .)
--- --- Handle Ret Msg
--- --- Split on Message Payload
--- (split  ({ C }) | (p(< NI | toKernel(msg(PP1,GPPI,MSG-RETURN-URL,U) @ T), A > NWC,WIS,NIS,MSG?)) = (true) by (PP1 ~p NI) = (true) and (PP1 ~p NI) = (false) .)
--- (split  ({ C }) | (p(< NI | toKernel(msg(PP1,GPPI,MSG-RETURN-URL,U)    ), A > NWC,WIS,NIS,MSG?)) = (true) by (PP1 ~p NI) = (true) and (PP1 ~p NI) = (false) .)
--- --- Ensure loading? flag is set
--- (split  ({ C }) | (p(< NI | toKernel(msg(NI,GPPI,MSG-RETURN-URL,U) @ T), A > NWC,WIS,NIS,MSG?)) = (true) by (proc-loaded?(NI,GPPI,NIS,WIS,NWC)) = (true) and (proc-loaded?(NI,GPPI,NIS,WIS,NWC)) = (false) .)
--- (split  ({ C }) | (p(< NI | toKernel(msg(NI,GPPI,MSG-RETURN-URL,U)    ), A > NWC,WIS,NIS,MSG?)) = (true) by (proc-loaded?(NI,GPPI,NIS,WIS,NWC)) = (true) and (proc-loaded?(NI,GPPI,NIS,WIS,NWC)) = (false) .)
--- --- Payload Split Part #2
--- (split  ({ C }) | (p(< NI | toKernel(msg(NI,GPPI,MSG-RETURN-URL,U) @ T), A > NWC,WIS,pi(NI,IN,OUT),np NIS,MSG?)) = (true) by (U ~l OUT) = (true) and (U ~l OUT) = (false) .)
--- (split  ({ C }) | (p(< NI | toKernel(msg(NI,GPPI,MSG-RETURN-URL,U)    ), A > NWC,WIS,pi(NI,IN,OUT),np NIS,MSG?)) = (true) by (U ~l OUT) = (true) and (U ~l OUT) = (false) .)
--- --- Link metadata pieces
--- (split  ({ < NI | A > < kernel | netlabels(pi(NI,IN2,OUT),np NIS), A' > C }) by (IN2 ~l OUT) = (true) and (IN2 ~l OUT) = (false) .)
--- ---
--- --- UI case
--- (cases+ ({ C }) | (ui-consistent?(msg(PP1,GPPI,MT:MsgType,U) @ T,WIS)) = (true) on MT:MsgType by (MSG-FETCH-URL) U (MSG-RETURN-URL) U (MSG-SWITCH-TAB) U (MSG-NEW-URL) .)
--- (cases+ ({ C }) | (ui-consistent?(msg(PP1,GPPI,MT:MsgType,U)    ,WIS)) = (true) on MT:MsgType by (MSG-FETCH-URL) U (MSG-RETURN-URL) U (MSG-SWITCH-TAB) U (MSG-NEW-URL) .)
--- --- NEW-URL
--- (split  ({ C }) | (ui-consistent?(msg(PP1,GPPI,MSG-NEW-URL,   U) @ T,WIS)) = (true) by (newurl-nodupl?(U,T)) = (true) and (newurl-nodupl?(U,T)) = (false) .)
--- (split  ({ C }) | (ui-consistent?(msg(PP1,GPPI,MSG-NEW-URL,   U) @ T,WIS)) = (true) by (GPPI ~p webapp) = (true) and (GPPI ~p webapp) = (false) .)
--- (split  ({ C }) | (ui-consistent?(msg(PP1,GPPI,MSG-NEW-URL,   U)    ,WIS)) = (true) by (GPPI ~p webapp) = (true) and (GPPI ~p webapp) = (false) .)
--- --- SWITCH-TAB
--- (split  ({ C }) | (ui-consistent?(msg(PP1,GPPI,MSG-SWITCH-TAB,U) @ T,WIS)) = (true) by (weblabel-by-pid(GPPI,WIS)) = (IN) and  (weblabel-by-pid(GPPI,WIS)) = (nolabel) .)
--- (split  ({ C }) | (ui-consistent?(msg(PP1,GPPI,MSG-SWITCH-TAB,U)    ,WIS)) = (true) by (weblabel-by-pid(GPPI,WIS)) = (IN) and  (weblabel-by-pid(GPPI,WIS)) = (nolabel) .)
--- ---
--- --- Finish
--- (auto .)

--- kernelForwardsOPMessage
--- (cases ({ < NWI:ConcNetWebProcId | fromKernel(F), A  > C }) on NWI:ConcNetWebProcId by (WI) U (NI) .)
--- --- NetProc Case
--- --- Split on Message Type
--- (cases ({ < NI | fromKernel(F @ msg(PP1,NI,MT:MsgType,   U)), A > C }) on MT:MsgType by (MSG-FETCH-URL) U (N:NonFetchMsgType) .)
--- --- Handle NonFetch Msg
--- (split ({ < NI | fromKernel(F @ msg(PP1,NI,N:NonFetchMsgType,U)), A > < kernel | netlabels(NIS), A' > C }) by (netlabelpair-by-pid(NI,NIS)) = ((IN,OUT)) and (netlabelpair-by-pid(NI,NIS)) = (nopair) .)
--- --- Handle Fetch Msg
--- (split ({ < NI | fromKernel(F @ msg(PP1,NI,MSG-FETCH-URL,U)), A > < kernel | netlabels(NIS), weblabels(WIS), A' > C }) by (proc-loaded?(NI,PP1,NIS,WIS,C)) = (true) and (proc-loaded?(NI,PP1,NIS,WIS,C)) = (false) .)
--- (split ({ < NI | fromKernel(F @ msg(PP1,NI,MSG-FETCH-URL,U)), A > < kernel | netlabels(pi(NI,IN,OUT),np NIS), A' > C }) by (U ~l OUT) = (true) and (U ~l OUT) = (false) .)
--- --- WebProc Case
--- --- Split on Message Type
--- (cases ({ < WI | fromKernel(F @ msg(PP1,WI,MT:MsgType,    U)), A > C }) on MT:MsgType by (MSG-RETURN-URL) U (N:NonRetMsgType) .)
--- --- Handle NonRet Msg
--- (split ({ < WI | fromKernel(F @ msg(PP1,WI,N:NonRetMsgType,U)), A > < kernel | weblabels(WIS), A' > C }) by (weblabel-by-pid(WI,WIS)) = (IN) and (weblabel-by-pid(WI,WIS)) = (nolabel) .)
--- --- Handle Ret Msg
--- (split ({ < WI | fromKernel(F @ msg(PP1,WI,MSG-RETURN-URL,U)), A > C }) by (in-conf?(PP1,C)) = (true) and (in-conf?(PP1,C)) = (false) .)
--- (split ({ < WI | fromKernel(F @ msg(PP1,WI,MSG-RETURN-URL,U)), A > < kernel | netlabels(NIS), weblabels(WIS), A' > C }) by (proc-loaded?(PP1,WI,NIS,WIS,C < WI | A >)) = (true) and (proc-loaded?(PP1,WI,NIS,WIS,C < WI | A >)) = (false) .)
--- (split ({ < WI | fromKernel(F @ msg(PP1,WI,MSG-RETURN-URL,U)), A > < kernel | netlabels(pi(NI,IN,OUT),np NIS), A' > C }) by (U ~l OUT) = (true) and (U ~l OUT) = (false) .)
--- --- Link metadata pieces
--- (split ({ < kernel | netlabels(pi(NI,IN,OUT),np NIS), A > C }) by (IN ~l OUT) = (true) and (IN ~l OUT) = (false) .)
--- ---
--- (auto .)
