load ibos-sop-fvp-noau.maude
load ibos-sop-noau.maude
load ibos-sop-pred-nou.maude

set show advisories off .
set print attribute on .
---set print with parentheses on .

load ../../rltool-lib.maude

fmod FOFORMSIMPLIFY-IMP-IMPL-EXT is
  pr FOFORMSIMPLIFY-IMP-IMPL .

  var D : Disj .
  var T T' : Term .
  var L L' : TermList .

  eq 'false.Bool ?= '_and_[T,T'] = 'false.Bool ?= T \/ 'false.Bool ?= T' .
  eq 'false.Bool != '_and_[T,T'] = 'false.Bool != T /\ 'false.Bool != T' .
  eq 'false.Bool ?= 'true.Bool = ff .
endfm

select RLTOOL .
loop rltl-init .

(select IBOS-SOP .)

--- Solved:
--- 1. kernelReceivesOPMessage-pa7-cc1b
--- 2. kernelReceivesOPMessage-pa7-cc1a
--- 3. kernelReceivesOPMessage-pa6-cc2b
--- 4. kernelReceivesOPMessage-pa6-cc2a
--- 5. new-url

--- Todo:
---(select-rls kernelForwardsOPMessage .)

--- Usage: select-rls ...
(select-rls kernelReceivesOPMessage-pa7-cc1a .)

(use tool conrew for validity on IBOS-SOP-PRED-NOID       with FOFORMSIMPLIFY-IMP-IMPL-EXT .)
(use tool varsat for validity on KERNEL-POLICIES-FVP-NOID .)
(declare-vars (C:NeConfiguration) U (WPIS:WebappProcInfoSet) U (NPIS:NetworkProcInfoSet) U (MSG:Message) U
              (PS:PolicySet) U (NNP:Nat) U (NWA:Nat) U (U:Label) U (B:Bool) U (B':Bool) .)
(def-term-set ([C]) | true .)
--- INV is a generalized multiset equality between:
--- [1] set of fromKernel messages at the beginning of a list in a netproc
--- [2] labels in WebappInfoSet and NetworkProcInfoSet
(inv sop4 to '`[_`] on
({ C
   < webappmgr | nextWAN(NWA) >
   < kernel | weblabels(WPIS), networklabels(NPIS), displayedTopBar(U), handledCurrently(MSG), msgPolicy(PS), nextNetworkProc(NNP) > } ) |
   --- p /\ p' encodes the SOP
   (p (C,WPIS,NPIS))                              = (true)   /\
   (mp(MSG,WPIS,NPIS,NNP,NWA))                    = (true)   /\
   --- these are strengthenings of the invariant above that allow the simplification rules to apply more often
   --- they are not strictly needed for correctness --- the invariant above should be enough
   (fresh-np-id?(NNP,C))                          = (true)   /\
   (fresh-wa-id?(NWA,C))                          = (true)   /\
   (dupl?(C < webappmgr | nextWAN(NWA)      >
            < kernel | nextNetworkProc(NNP) >))   = (false)
.)
(start-proof .)
set break on .
break select simp-action .
set print conceal on .
print conceal fmod_is_sorts_.____endfm mod_is_sorts_._____endm .
--- Apparently, the kernel is duplicated in many matches, we could create a new subsort to solve that problem
(auto .)
--- cc1a
--- (cases ({< kernel | handledCurrently(msg(N:NetProcId,W:WebAppId,MT:MsgType,OUT:Label)), AS:AttributeSet > C}) on MT:MsgType by (MSG-RETURN-URL) U (NR:NonRetMsg) .)
--- (auto .)
---(
--- (list-goals .)
--- quit .
--- (cases+ ({C}) | ((true) = (B' a (B o (false ~ (MSG-RETURN-URL ~ MT:MsgType))))) on MT:MsgType by (MSG-RETURN-URL) U (NR:NonRetMsg) .)
---)
