#!/bin/bash

FULL_MAUDE_PATH="../../full-maude-removeids.maude"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR"

function remove_all_ids() {
if [ $# -ne 3 ]; then
  echo "remove_ids() argument error"
fi

FILE_PATH=$1
MODULE_NAME=$2
OUTPUT_FILE_NAME=$3

echo "Removing all identities from $1:$2"

maude <<INPUT |
load ${FILE_PATH}.maude
load ${FULL_MAUDE_PATH}
loop init .
(remove ${ARGUMENT} identity attributes ${MODULE_NAME} .)
quit
INPUT
tail -n+4 | head -n-2 | sed -E '1s/^fmod (\S+) is/set include BOOL off .\n\nfmod \1-NOID is/' > "${OUTPUT_FILE_NAME}.maude"
}

function remove_unhandled_ids() {
if [ $# -ne 3 ]; then
  echo "remove_ids() argument error"
fi

FILE_PATH=$1
MODULE_NAME=$2
OUTPUT_FILE_NAME=$3

echo "Removing unhandled identities from $1:$2"

maude <<INPUT |
load ${FILE_PATH}.maude
load ${FULL_MAUDE_PATH}
loop init .
(remove non-handled identity attributes ${MODULE_NAME} .)
quit
INPUT
tail -n+4 | head -n-2 | sed -E '1s/^(f?mod \S+) is/set include BOOL off .\n\n\1-NOID is/' > "${OUTPUT_FILE_NAME}.maude"
}

remove_unhandled_ids "./ibos-preds" "IBOS-PREDS-FVP"       "../../systems/ibos-preds-fvp-noau" # varsat
remove_all_ids       "./ibos-preds" "IBOS-PREDS"           "../../systems/ibos-preds-nou"      # contextual rewriting
remove_unhandled_ids "./ibos-preds" "IBOS-STOP-WITH-PREDS" "../../systems/ibos-noau"           # everything
